/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Banner with image and link to redirect users.
 *
 * @param image
 * @param link
 */
@Serializable
public data class Banner(
  @SerialName(value = "image") val image: BannerImage? = null,
  @SerialName(value = "link") val link: BannerLink? = null,
) {}
