/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * CompositionIdRankingInfo
 *
 * @param index
 * @param injectedItemKey
 */
@Serializable
public data class CompositionIdRankingInfo(
  @SerialName(value = "index") val index: String,
  @SerialName(value = "injectedItemKey") val injectedItemKey: String,
) {}
