/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * CompositionRunAppliedRules
 *
 * @param objectID The objectID of the applied composition rule on this query.
 */
@Serializable
public data class CompositionRunAppliedRules(

  /** The objectID of the applied composition rule on this query. */
  @SerialName(value = "objectID") val objectID: String
) {}
