/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*

@Serializable
public enum class ExternalOrdering(public val value: kotlin.String) {

  @SerialName(value = "default") Default("default"),
  @SerialName(value = "userDefined") UserDefined("userDefined");

  override fun toString(): kotlin.String = value
}
