/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Used to add metadata to the results of the injectedItem.
 *
 * @param hits
 */
@Serializable
public data class InjectedItemMetadata(
  @SerialName(value = "hits") val hits: InjectedItemHitsMetadata? = null
) {}
