/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ResultsInjectedItemAppliedRulesInfoResponse
 *
 * @param objectID The objectID of the applied index level rule on this injected group.
 */
@Serializable
public data class ResultsInjectedItemAppliedRulesInfoResponse(

  /** The objectID of the applied index level rule on this injected group. */
  @SerialName(value = "objectID") val objectID: String
) {}
