/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * RulesMultipleBatchRequest
 *
 * @param action
 * @param body
 */
@Serializable
public data class RulesMultipleBatchRequest(
  @SerialName(value = "action") val action: Action,
  @SerialName(value = "body") val body: RulesBatchCompositionAction,
) {}
