/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import com.flapjackhq.client.exception.AlgoliaClientException
import com.flapjackhq.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * RulesBatchCompositionAction
 *
 * Implementations:
 * - [CompositionRule]
 * - [DeleteCompositionRuleAction]
 */
@Serializable(RulesBatchCompositionActionSerializer::class)
public sealed interface RulesBatchCompositionAction {
  @Serializable
  @JvmInline
  public value class CompositionRuleValue(public val value: CompositionRule) :
    RulesBatchCompositionAction

  @Serializable
  @JvmInline
  public value class DeleteCompositionRuleActionValue(
    public val value: DeleteCompositionRuleAction
  ) : RulesBatchCompositionAction

  public companion object {

    public fun of(value: CompositionRule): RulesBatchCompositionAction = CompositionRuleValue(value)

    public fun of(value: DeleteCompositionRuleAction): RulesBatchCompositionAction =
      DeleteCompositionRuleActionValue(value)
  }
}

internal class RulesBatchCompositionActionSerializer :
  JsonContentPolymorphicSerializer<RulesBatchCompositionAction>(
    RulesBatchCompositionAction::class
  ) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<RulesBatchCompositionAction> {
    return when {
      element is JsonObject -> CompositionRule.serializer()
      element is JsonObject -> DeleteCompositionRuleAction.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
