/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * SearchForFacetValuesRequest
 *
 * @param params
 */
@Serializable
public data class SearchForFacetValuesRequest(
  @SerialName(value = "params") val params: SearchForFacetValuesParams? = null
) {}
