/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.composition

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Injected items will originate from a search request performed on the specified index.
 *
 * @param search
 */
@Serializable
public data class SearchSource(@SerialName(value = "search") val search: Search) :
  InjectedItemSource {}
