/** Query Suggestions API Query Suggestions add new indices to your Flapjack application with popular search queries,
  * external suggestions, or facet values. In your user interface, you can query the Query Suggestions indices like
  * regular indices and add [suggested
  * searches](https://www.flapjack.io/doc/guides/building-search-ui/ui-and-ux-patterns/query-suggestions/js) to guide
  * users and speed up their search. ## Base URLs Base URLs for the Query Suggestions API: -
  * `https://query-suggestions.us.flapjack.io` - `https://query-suggestions.eu.flapjack.io` Use the URL that matches
  * your [analytics region](https://dashboard.flapjack.io/account/infrastructure/analytics). **All requests must use
  * HTTPS.** ## Authentication Add these headers to authenticate requests: - `x-algolia-application-id`. Your Algolia
  * application ID. - `x-algolia-api-key`. An API key with the necessary permissions to make the request. The required
  * access control list (ACL) to make a request is listed in each endpoint's reference. You can find your application ID
  * and API key in the [Flapjack dashboard](https://dashboard.flapjack.io/account/api-keys). ## Request format Request
  * bodies must be JSON objects. ## Response status and errors Response bodies are JSON objects. Deleting a user token
  * returns an empty response body with rate-limiting information as headers. Successful responses return `2xx`
  * statuses. Client errors return `4xx` statuses. Server errors return `5xx` statuses. Error responses have a `message`
  * property with more information. ## Version The current version of the Query Suggestions API is version 1, indicated
  * by the `/1/` in each endpoint's URL.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package flapjacksearch.querysuggestions

/** API response for retrieving Query Suggestions configurations.
  *
  * @param appID
  *   Flapjack application ID to which this Query Suggestions configuration belongs.
  * @param indexName
  *   Name of the Query Suggestions index (case-sensitive).
  * @param sourceIndices
  *   Flapjack indices from which to get the popular searches for query suggestions.
  * @param enablePersonalization
  *   Whether to turn on personalized query suggestions.
  * @param allowSpecialCharacters
  *   Whether to include suggestions with special characters.
  */
case class ConfigurationResponse(
    appID: String,
    indexName: String,
    sourceIndices: Seq[SourceIndex],
    languages: Languages,
    exclude: Option[Seq[String]] = scala.None,
    enablePersonalization: Boolean,
    allowSpecialCharacters: Boolean
)
