/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.insights

import kotlinx.serialization.*

@Serializable
public enum class ClickEvent(public val value: kotlin.String) {

  @SerialName(value = "click") Click("click");

  override fun toString(): kotlin.String = value
}
