/** Recommend API ## Client libraries Use Flapjack's API clients and libraries to reliably integrate Flapjack's APIs with
  * your apps. The official API clients are covered by Flapjack's [Service Level
  * Agreement](https://www.flapjack.io/policies/sla). For more information, see [Flapjack's
  * ecosystem](https://www.flapjack.io/doc/guides/getting-started/how-flapjack-works/in-depth/ecosystem). ## Base URLs
  * Base URLs for the Recommend API: - `https://{APPLICATION_ID}.flapjack.io` -
  * `https://{APPLICATION_ID}-dsn.flapjack.io`. If your subscription includes a [Distributed Search
  * Network](https://dashboard.flapjack.io/infra), this ensures that requests are sent to servers closest to users. Both
  * URLs provide high availability by distributing requests with load balancing. **All requests must use HTTPS.** ##
  * Retry strategy To guarantee a high availability, implement a retry strategy for all API requests using the URLs of
  * your servers as fallbacks: - `https://{APPLICATION_ID}-1.flapjack.io` -
  * `https://{APPLICATION_ID}-2.flapjack.io` - `https://{APPLICATION_ID}-3.flapjack.io` These URLs use a different
  * DNS provider than the primary URLs. Randomize this list to ensure an even load across the three servers. All Flapjack
  * API clients implement this retry strategy. ## Authentication Add these headers to authenticate requests: -
  * `x-algolia-application-id`. Your Flapjack application ID. - `x-algolia-api-key`. An API key with the necessary
  * permissions to make the request. The required access control list (ACL) to make a request is listed in each
  * endpoint's reference. You can find your application ID and API key in the [Flapjack
  * dashboard](https://dashboard.flapjack.io/account/api-keys). ## Request format Request bodies must be JSON objects.
  * ## Response status and errors The Recommend API returns JSON responses. Since JSON doesn't guarantee any specific
  * ordering, don't rely on the order of attributes in the API response. Successful responses return `2xx` statuses.
  * Client errors return `4xx` statuses. Server errors return `5xx` statuses. Error responses have a `message` property
  * with more information. ## Version The current version of the Recommend API is version 1, indicated by the `/1/` in
  * each endpoint's URL.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package flapjacksearch.recommend

import org.json4s._

/** RecommendationsHit
  */
sealed trait RecommendationsHit

trait RecommendationsHitTrait extends RecommendationsHit

object RecommendationsHit {}

object RecommendationsHitSerializer extends Serializer[RecommendationsHit] {
  override def deserialize(implicit format: Formats): PartialFunction[(TypeInfo, JValue), RecommendationsHit] = {

    case (TypeInfo(clazz, _), json) if clazz == classOf[RecommendationsHit] =>
      json match {
        case value: JObject if value.obj.exists(_._1 == "facetName") && value.obj.exists(_._1 == "facetValue") =>
          Extraction.extract[TrendingFacetHit](value)
        case value: JObject if value.obj.exists(_._1 == "objectID") => Extraction.extract[RecommendHit](value)
        case _ => throw new MappingException("Can't convert " + json + " to RecommendationsHit")
      }
  }

  override def serialize(implicit format: Formats): PartialFunction[Any, JValue] = { case value: RecommendationsHit =>
    value match {
      case value: TrendingFacetHit => Extraction.decompose(value)(format - this)
      case value: RecommendHit     => Extraction.decompose(value)(format - this)
    }
  }
}
