<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

namespace Flapjack\FlapjackSearch\Model\Insights;

/**
 * PurchaseEvent Class Doc Comment.
 *
 * @category Class
 */
class PurchaseEvent
{
    /**
     * Possible values of this enum.
     */
    public const PURCHASE = 'purchase';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PURCHASE,
        ];
    }
}
