/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.monitoring

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * IndexingTimeResponse
 *
 * @param metrics
 */
@Serializable
public data class IndexingTimeResponse(
  @SerialName(value = "metrics") val metrics: IndexingMetric? = null
) {}
