/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.monitoring

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ProbesMetric
 *
 * @param t Timestamp, measured in milliseconds since the Unix epoch.
 * @param v Value of the metric.
 */
@Serializable
public data class ProbesMetric(

  /** Timestamp, measured in milliseconds since the Unix epoch. */
  @SerialName(value = "t") val t: Long? = null,

  /** Value of the metric. */
  @SerialName(value = "v") val v: Int? = null,
) {}
