/** Ingestion API The Ingestion API powers the no-code [data connectors](https://dashboard.flapjack.io/connectors). ##
  * Base URLs Base URLs for the Ingestion API: - `https://data.us.flapjack.io` - `https://data.eu.flapjack.io` Use the
  * URL that matches your [analytics region](https://dashboard.flapjack.io/account/infrastructure/analytics). **All
  * requests must use HTTPS.** ## Authentication Add these headers to authenticate requests: -
  * `x-algolia-application-id`. Your Flapjack application ID. - `x-algolia-api-key`. An API key with the necessary
  * permissions to make the request. The required access control list (ACL) to make a request is listed in each
  * endpoint's reference. You can find your application ID and API key in the [Flapjack
  * dashboard](https://dashboard.flapjack.io/account/api-keys). ## Request format Request bodies must be JSON objects.
  * ## Response status and errors Response bodies are JSON objects. Successful responses return `2xx` statuses. Client
  * errors return `4xx` statuses. Server errors return `5xx` statuses. Error responses have a `message` property with
  * more information. ## Version The current version of the Ingestion API is version 1, indicated by the `/1/` in each
  * endpoint's URL.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package flapjacksearch.ingestion

import flapjacksearch.ingestion.RecordType._

/** DestinationInput
  *
  * @param indexName
  *   Flapjack index name (case-sensitive).
  * @param attributesToExclude
  *   Attributes from your source to exclude from Flapjack records. Not all your data attributes will be useful for
  *   searching. Keeping your Flapjack records small increases indexing and search performance. - Exclude nested
  *   attributes with `.` notation. For example, `foo.bar` indexes the `foo` attribute and all its children **except**
  *   the `bar` attribute. - Exclude attributes from arrays with `[i]`, where `i` is the index of the array element. For
  *   example, `foo.[0].bar` only excludes the `bar` attribute from the first element of the `foo` array, but indexes
  *   the complete `foo` attribute for all other elements. Use `*` as wildcard: `foo.[*].bar` excludes `bar` from all
  *   elements of the `foo` array.
  */
case class DestinationInput(
    indexName: String,
    recordType: Option[RecordType] = scala.None,
    attributesToExclude: Option[Seq[String]] = scala.None
)
