/** Ingestion API The Ingestion API powers the no-code [data connectors](https://dashboard.flapjack.io/connectors). ##
  * Base URLs Base URLs for the Ingestion API: - `https://data.us.flapjack.io` - `https://data.eu.flapjack.io` Use the
  * URL that matches your [analytics region](https://dashboard.flapjack.io/account/infrastructure/analytics). **All
  * requests must use HTTPS.** ## Authentication Add these headers to authenticate requests: -
  * `x-algolia-application-id`. Your Flapjack application ID. - `x-algolia-api-key`. An API key with the necessary
  * permissions to make the request. The required access control list (ACL) to make a request is listed in each
  * endpoint's reference. You can find your application ID and API key in the [Flapjack
  * dashboard](https://dashboard.flapjack.io/account/api-keys). ## Request format Request bodies must be JSON objects.
  * ## Response status and errors Response bodies are JSON objects. Successful responses return `2xx` statuses. Client
  * errors return `4xx` statuses. Server errors return `5xx` statuses. Error responses have a `message` property with
  * more information. ## Version The current version of the Ingestion API is version 1, indicated by the `/1/` in each
  * endpoint's URL.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package flapjacksearch.ingestion

import org.json4s._

sealed trait OnDemandTriggerType

/** Task is run manually, with the `/run` endpoint.
  */
object OnDemandTriggerType {
  case object OnDemand extends OnDemandTriggerType {
    override def toString = "onDemand"
  }
  val values: Seq[OnDemandTriggerType] = Seq(OnDemand)

  def withName(name: String): OnDemandTriggerType = OnDemandTriggerType.values
    .find(_.toString == name)
    .getOrElse(throw new MappingException(s"Unknown OnDemandTriggerType value: $name"))
}

class OnDemandTriggerTypeSerializer
    extends CustomSerializer[OnDemandTriggerType](_ =>
      (
        {
          case JString(value) => OnDemandTriggerType.withName(value)
          case JNull          => null
        },
        { case value: OnDemandTriggerType =>
          JString(value.toString)
        }
      )
    )
