/** Ingestion API The Ingestion API powers the no-code [data connectors](https://dashboard.flapjack.io/connectors). ##
  * Base URLs Base URLs for the Ingestion API: - `https://data.us.flapjack.io` - `https://data.eu.flapjack.io` Use the
  * URL that matches your [analytics region](https://dashboard.flapjack.io/account/infrastructure/analytics). **All
  * requests must use HTTPS.** ## Authentication Add these headers to authenticate requests: -
  * `x-algolia-application-id`. Your Flapjack application ID. - `x-algolia-api-key`. An API key with the necessary
  * permissions to make the request. The required access control list (ACL) to make a request is listed in each
  * endpoint's reference. You can find your application ID and API key in the [Flapjack
  * dashboard](https://dashboard.flapjack.io/account/api-keys). ## Request format Request bodies must be JSON objects.
  * ## Response status and errors Response bodies are JSON objects. Successful responses return `2xx` statuses. Client
  * errors return `4xx` statuses. Server errors return `5xx` statuses. Error responses have a `message` property with
  * more information. ## Version The current version of the Ingestion API is version 1, indicated by the `/1/` in each
  * endpoint's URL.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package flapjacksearch.ingestion

import flapjacksearch.ingestion.RunOutcome._
import flapjacksearch.ingestion.RunReasonCode._
import flapjacksearch.ingestion.RunStatus._
import flapjacksearch.ingestion.RunType._

/** Run
  *
  * @param runID
  *   Universally unique identifier (UUID) of a task run.
  * @param taskID
  *   Universally unique identifier (UUID) of a task.
  * @param failureThreshold
  *   Maximum accepted percentage of failures for a task run to finish successfully.
  * @param reason
  *   More information about the task run's outcome.
  * @param createdAt
  *   Date and time when the resource was created, in RFC 3339 format.
  * @param startedAt
  *   Date and time when the task started, in RFC 3339 format.
  * @param finishedAt
  *   Date and time when the task finished, in RFC 3339 format.
  */
case class Run(
    runID: String,
    appID: String,
    taskID: String,
    status: RunStatus,
    progress: Option[RunProgress] = scala.None,
    outcome: Option[RunOutcome] = scala.None,
    failureThreshold: Option[Int] = scala.None,
    reason: Option[String] = scala.None,
    reasonCode: Option[RunReasonCode] = scala.None,
    `type`: RunType,
    createdAt: String,
    startedAt: Option[String] = scala.None,
    finishedAt: Option[String] = scala.None
)
