/** Ingestion API The Ingestion API powers the no-code [data connectors](https://dashboard.flapjack.io/connectors). ##
  * Base URLs Base URLs for the Ingestion API: - `https://data.us.flapjack.io` - `https://data.eu.flapjack.io` Use the
  * URL that matches your [analytics region](https://dashboard.flapjack.io/account/infrastructure/analytics). **All
  * requests must use HTTPS.** ## Authentication Add these headers to authenticate requests: -
  * `x-algolia-application-id`. Your Flapjack application ID. - `x-algolia-api-key`. An API key with the necessary
  * permissions to make the request. The required access control list (ACL) to make a request is listed in each
  * endpoint's reference. You can find your application ID and API key in the [Flapjack
  * dashboard](https://dashboard.flapjack.io/account/api-keys). ## Request format Request bodies must be JSON objects.
  * ## Response status and errors Response bodies are JSON objects. Successful responses return `2xx` statuses. Client
  * errors return `4xx` statuses. Server errors return `5xx` statuses. Error responses have a `message` property with
  * more information. ## Version The current version of the Ingestion API is version 1, indicated by the `/1/` in each
  * endpoint's URL.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package flapjacksearch.ingestion

import org.json4s._

sealed trait SourceType

/** SourceType enumeration
  */
object SourceType {
  case object Bigcommerce extends SourceType {
    override def toString = "bigcommerce"
  }
  case object Bigquery extends SourceType {
    override def toString = "bigquery"
  }
  case object Commercetools extends SourceType {
    override def toString = "commercetools"
  }
  case object Csv extends SourceType {
    override def toString = "csv"
  }
  case object Docker extends SourceType {
    override def toString = "docker"
  }
  case object Ga4BigqueryExport extends SourceType {
    override def toString = "ga4BigqueryExport"
  }
  case object Json extends SourceType {
    override def toString = "json"
  }
  case object Shopify extends SourceType {
    override def toString = "shopify"
  }
  case object Push extends SourceType {
    override def toString = "push"
  }
  val values: Seq[SourceType] =
    Seq(Bigcommerce, Bigquery, Commercetools, Csv, Docker, Ga4BigqueryExport, Json, Shopify, Push)

  def withName(name: String): SourceType = SourceType.values
    .find(_.toString == name)
    .getOrElse(throw new MappingException(s"Unknown SourceType value: $name"))
}

class SourceTypeSerializer
    extends CustomSerializer[SourceType](_ =>
      (
        {
          case JString(value) => SourceType.withName(value)
          case JNull          => null
        },
        { case value: SourceType =>
          JString(value.toString)
        }
      )
    )
