# frozen_string_literal: true

# Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

# Common files
require "flapjack/api_client"
require "flapjack/api_error"
require "flapjack/defaults"
require "flapjack/error"
require "flapjack/version"
require "flapjack/configuration"
require "flapjack/user_agent"
require "flapjack/logger_helper"
require "flapjack/transport/http/http_requester"
require "flapjack/transport/http/response"
require "flapjack/transport/echo_requester"
require "flapjack/transport/call_type"
require "flapjack/transport/retry_outcome_type"
require "flapjack/transport/stateful_host"
require "flapjack/transport/retry_strategy"
require "flapjack/transport/request_options"
require "flapjack/transport/transport"

# Models
Dir["#{File.dirname(__FILE__)}/flapjack/models/**/*.rb"].sort.each { |file| require file }

# APIs
Dir["#{File.dirname(__FILE__)}/flapjack/api/*.rb"].sort.each { |file| require file }

module Flapjack
end
