// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

package com.flapjackhq.api;

import com.flapjackhq.ApiClient;
import com.flapjackhq.config.*;
import com.flapjackhq.config.ClientOptions;
import com.flapjackhq.exceptions.*;
import com.flapjackhq.model.insights.*;
import com.flapjackhq.utils.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.time.Duration;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import okhttp3.Response;

public class InsightsClient extends ApiClient {

  private static final String[] allowedRegions = { "de", "us" };

  public InsightsClient(String appId, String apiKey) {
    this(appId, apiKey, null, null);
  }

  public InsightsClient(String appId, String apiKey, ClientOptions options) {
    this(appId, apiKey, null, options);
  }

  public InsightsClient(String appId, String apiKey, String region) {
    this(appId, apiKey, region, null);
  }

  public InsightsClient(String appId, String apiKey, String region, ClientOptions options) {
    super(
      appId,
      apiKey,
      "Insights",
      options,
      getDefaultHosts(region),
      Duration.ofMillis(2000L),
      Duration.ofMillis(5000L),
      Duration.ofMillis(30000L)
    );
  }

  private static List<Host> getDefaultHosts(String region) throws FlapjackRuntimeException {
    List<Host> hosts = new ArrayList<>();

    boolean found = region == null;
    if (region != null) {
      for (String allowed : allowedRegions) {
        if (allowed.equals(region)) {
          found = true;
          break;
        }
      }
    }

    if (!found) {
      throw new FlapjackRuntimeException("`region` must be one of the following: de, us");
    }

    String url = region == null ? "insights.algolia.io" : "insights.{region}.algolia.io".replace("{region}", region);

    hosts.add(new Host(url, EnumSet.of(CallType.READ, CallType.WRITE)));
    return hosts;
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customDelete(@Nonnull String path, Map<String, Object> parameters, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(customDeleteAsync(path, parameters, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customDeleteWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(customDeleteWithHTTPInfoAsync(path, parameters, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customDelete(@Nonnull String path, Map<String, Object> parameters) throws FlapjackRuntimeException {
    return this.customDelete(path, parameters, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customDeleteWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters) throws FlapjackRuntimeException {
    return this.customDeleteWithHTTPInfo(path, parameters, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customDelete(@Nonnull String path, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    return this.customDelete(path, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customDeleteWithHTTPInfo(@Nonnull String path, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    return this.customDeleteWithHTTPInfo(path, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customDelete(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customDelete(path, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customDeleteWithHTTPInfo(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customDeleteWithHTTPInfo(path, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customDeleteAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customDelete`.");

    HttpRequest request = HttpRequest.builder().setPathEncoded("/{path}", path).setMethod("DELETE").addQueryParameters(parameters).build();
    return executeAsync(request, requestOptions, new TypeReference<Object>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customDeleteWithHTTPInfoAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customDelete`.");

    HttpRequest request = HttpRequest.builder().setPathEncoded("/{path}", path).setMethod("DELETE").addQueryParameters(parameters).build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customDeleteAsync(@Nonnull String path, Map<String, Object> parameters) throws FlapjackRuntimeException {
    return this.customDeleteAsync(path, parameters, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customDeleteWithHTTPInfoAsync(@Nonnull String path, Map<String, Object> parameters)
    throws FlapjackRuntimeException {
    return this.customDeleteWithHTTPInfoAsync(path, parameters, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customDeleteAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return this.customDeleteAsync(path, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customDeleteWithHTTPInfoAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return this.customDeleteWithHTTPInfoAsync(path, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customDeleteAsync(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customDeleteAsync(path, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customDeleteWithHTTPInfoAsync(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customDeleteWithHTTPInfoAsync(path, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customGet(@Nonnull String path, Map<String, Object> parameters, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(customGetAsync(path, parameters, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customGetWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(customGetWithHTTPInfoAsync(path, parameters, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customGet(@Nonnull String path, Map<String, Object> parameters) throws FlapjackRuntimeException {
    return this.customGet(path, parameters, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customGetWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters) throws FlapjackRuntimeException {
    return this.customGetWithHTTPInfo(path, parameters, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customGet(@Nonnull String path, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    return this.customGet(path, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customGetWithHTTPInfo(@Nonnull String path, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    return this.customGetWithHTTPInfo(path, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customGet(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customGet(path, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customGetWithHTTPInfo(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customGetWithHTTPInfo(path, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customGetAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customGet`.");

    HttpRequest request = HttpRequest.builder().setPathEncoded("/{path}", path).setMethod("GET").addQueryParameters(parameters).build();
    return executeAsync(request, requestOptions, new TypeReference<Object>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customGetWithHTTPInfoAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customGet`.");

    HttpRequest request = HttpRequest.builder().setPathEncoded("/{path}", path).setMethod("GET").addQueryParameters(parameters).build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customGetAsync(@Nonnull String path, Map<String, Object> parameters) throws FlapjackRuntimeException {
    return this.customGetAsync(path, parameters, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customGetWithHTTPInfoAsync(@Nonnull String path, Map<String, Object> parameters)
    throws FlapjackRuntimeException {
    return this.customGetWithHTTPInfoAsync(path, parameters, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customGetAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return this.customGetAsync(path, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customGetWithHTTPInfoAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return this.customGetWithHTTPInfoAsync(path, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customGetAsync(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customGetAsync(path, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customGetWithHTTPInfoAsync(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customGetWithHTTPInfoAsync(path, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customPost(@Nonnull String path, Map<String, Object> parameters, Object body, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(customPostAsync(path, parameters, body, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customPostWithHTTPInfo(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    return LaunderThrowable.await(customPostWithHTTPInfoAsync(path, parameters, body, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customPost(@Nonnull String path, Map<String, Object> parameters, Object body) throws FlapjackRuntimeException {
    return this.customPost(path, parameters, body, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customPostWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters, Object body) throws FlapjackRuntimeException {
    return this.customPostWithHTTPInfo(path, parameters, body, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customPost(@Nonnull String path, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    return this.customPost(path, null, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customPostWithHTTPInfo(@Nonnull String path, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    return this.customPostWithHTTPInfo(path, null, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customPost(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customPost(path, null, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customPostWithHTTPInfo(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customPostWithHTTPInfo(path, null, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPostAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customPost`.");

    HttpRequest request = HttpRequest.builder()
      .setPathEncoded("/{path}", path)
      .setMethod("POST")
      .setBody(body)
      .addQueryParameters(parameters)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Object>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPostWithHTTPInfoAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customPost`.");

    HttpRequest request = HttpRequest.builder()
      .setPathEncoded("/{path}", path)
      .setMethod("POST")
      .setBody(body)
      .addQueryParameters(parameters)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPostAsync(@Nonnull String path, Map<String, Object> parameters, Object body)
    throws FlapjackRuntimeException {
    return this.customPostAsync(path, parameters, body, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPostWithHTTPInfoAsync(@Nonnull String path, Map<String, Object> parameters, Object body)
    throws FlapjackRuntimeException {
    return this.customPostWithHTTPInfoAsync(path, parameters, body, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPostAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return this.customPostAsync(path, null, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPostWithHTTPInfoAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return this.customPostWithHTTPInfoAsync(path, null, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPostAsync(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customPostAsync(path, null, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPostWithHTTPInfoAsync(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customPostWithHTTPInfoAsync(path, null, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customPut(@Nonnull String path, Map<String, Object> parameters, Object body, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(customPutAsync(path, parameters, body, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customPutWithHTTPInfo(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    return LaunderThrowable.await(customPutWithHTTPInfoAsync(path, parameters, body, requestOptions));
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customPut(@Nonnull String path, Map<String, Object> parameters, Object body) throws FlapjackRuntimeException {
    return this.customPut(path, parameters, body, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customPutWithHTTPInfo(@Nonnull String path, Map<String, Object> parameters, Object body) throws FlapjackRuntimeException {
    return this.customPutWithHTTPInfo(path, parameters, body, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customPut(@Nonnull String path, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    return this.customPut(path, null, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customPutWithHTTPInfo(@Nonnull String path, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    return this.customPutWithHTTPInfo(path, null, null, requestOptions);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Object customPut(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customPut(path, null, null, null);
  }

  /**
   * This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response customPutWithHTTPInfo(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customPutWithHTTPInfo(path, null, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPutAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customPut`.");

    HttpRequest request = HttpRequest.builder()
      .setPathEncoded("/{path}", path)
      .setMethod("PUT")
      .setBody(body)
      .addQueryParameters(parameters)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Object>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPutWithHTTPInfoAsync(
    @Nonnull String path,
    Map<String, Object> parameters,
    Object body,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(path, "Parameter `path` is required when calling `customPut`.");

    HttpRequest request = HttpRequest.builder()
      .setPathEncoded("/{path}", path)
      .setMethod("PUT")
      .setBody(body)
      .addQueryParameters(parameters)
      .build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPutAsync(@Nonnull String path, Map<String, Object> parameters, Object body)
    throws FlapjackRuntimeException {
    return this.customPutAsync(path, parameters, body, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param parameters Query parameters to apply to the current query. (optional)
   * @param body Parameters to send with the custom request. (optional)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPutWithHTTPInfoAsync(@Nonnull String path, Map<String, Object> parameters, Object body)
    throws FlapjackRuntimeException {
    return this.customPutWithHTTPInfoAsync(path, parameters, body, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPutAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return this.customPutAsync(path, null, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPutWithHTTPInfoAsync(@Nonnull String path, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return this.customPutWithHTTPInfoAsync(path, null, null, requestOptions);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Object> customPutAsync(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customPutAsync(path, null, null, null);
  }

  /**
   * (asynchronously) This method lets you send requests to the Algolia REST API.
   *
   * @param path Path of the endpoint, for example `1/newFeature`. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> customPutWithHTTPInfoAsync(@Nonnull String path) throws FlapjackRuntimeException {
    return this.customPutWithHTTPInfoAsync(path, null, null, null);
  }

  /**
   * Deletes all events related to the specified user token from events metrics and analytics. The
   * deletion is asynchronous, and processed within 48 hours. To delete a personalization user
   * profile, see `Delete a user profile` in the Personalization API.
   *
   * @param userToken User token for which to delete all associated events. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public void deleteUserToken(@Nonnull String userToken, @Nullable RequestOptions requestOptions) throws FlapjackRuntimeException {
    LaunderThrowable.await(deleteUserTokenAsync(userToken, requestOptions));
    return;
  }

  /**
   * Deletes all events related to the specified user token from events metrics and analytics. The
   * deletion is asynchronous, and processed within 48 hours. To delete a personalization user
   * profile, see `Delete a user profile` in the Personalization API.
   *
   * @param userToken User token for which to delete all associated events. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response deleteUserTokenWithHTTPInfo(@Nonnull String userToken, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(deleteUserTokenWithHTTPInfoAsync(userToken, requestOptions));
  }

  /**
   * Deletes all events related to the specified user token from events metrics and analytics. The
   * deletion is asynchronous, and processed within 48 hours. To delete a personalization user
   * profile, see `Delete a user profile` in the Personalization API.
   *
   * @param userToken User token for which to delete all associated events. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public void deleteUserToken(@Nonnull String userToken) throws FlapjackRuntimeException {
    this.deleteUserToken(userToken, null);
  }

  /**
   * Deletes all events related to the specified user token from events metrics and analytics. The
   * deletion is asynchronous, and processed within 48 hours. To delete a personalization user
   * profile, see `Delete a user profile` in the Personalization API.
   *
   * @param userToken User token for which to delete all associated events. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response deleteUserTokenWithHTTPInfo(@Nonnull String userToken) throws FlapjackRuntimeException {
    return this.deleteUserTokenWithHTTPInfo(userToken, null);
  }

  /**
   * (asynchronously) Deletes all events related to the specified user token from events metrics and
   * analytics. The deletion is asynchronous, and processed within 48 hours. To delete a
   * personalization user profile, see `Delete a user profile` in the Personalization API.
   *
   * @param userToken User token for which to delete all associated events. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Void> deleteUserTokenAsync(@Nonnull String userToken, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    Parameters.requireNonNull(userToken, "Parameter `userToken` is required when calling `deleteUserToken`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/usertokens/{userToken}", userToken).setMethod("DELETE").build();
    return executeAsync(request, requestOptions, null);
  }

  /**
   * (asynchronously) Deletes all events related to the specified user token from events metrics and
   * analytics. The deletion is asynchronous, and processed within 48 hours. To delete a
   * personalization user profile, see `Delete a user profile` in the Personalization API.
   *
   * @param userToken User token for which to delete all associated events. (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> deleteUserTokenWithHTTPInfoAsync(@Nonnull String userToken, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    Parameters.requireNonNull(userToken, "Parameter `userToken` is required when calling `deleteUserToken`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/usertokens/{userToken}", userToken).setMethod("DELETE").build();
    return executeAsync(request, requestOptions, null);
  }

  /**
   * (asynchronously) Deletes all events related to the specified user token from events metrics and
   * analytics. The deletion is asynchronous, and processed within 48 hours. To delete a
   * personalization user profile, see `Delete a user profile` in the Personalization API.
   *
   * @param userToken User token for which to delete all associated events. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Void> deleteUserTokenAsync(@Nonnull String userToken) throws FlapjackRuntimeException {
    return this.deleteUserTokenAsync(userToken, null);
  }

  /**
   * (asynchronously) Deletes all events related to the specified user token from events metrics and
   * analytics. The deletion is asynchronous, and processed within 48 hours. To delete a
   * personalization user profile, see `Delete a user profile` in the Personalization API.
   *
   * @param userToken User token for which to delete all associated events. (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> deleteUserTokenWithHTTPInfoAsync(@Nonnull String userToken) throws FlapjackRuntimeException {
    return this.deleteUserTokenWithHTTPInfoAsync(userToken, null);
  }

  /**
   * Sends a list of events to the Insights API. You can include up to 1,000 events in a single
   * request, but the request body must be smaller than 2&nbsp;MB.
   *
   * @param insightsEvents (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public EventsResponse pushEvents(@Nonnull InsightsEvents insightsEvents, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(pushEventsAsync(insightsEvents, requestOptions));
  }

  /**
   * Sends a list of events to the Insights API. You can include up to 1,000 events in a single
   * request, but the request body must be smaller than 2&nbsp;MB.
   *
   * @param insightsEvents (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response pushEventsWithHTTPInfo(@Nonnull InsightsEvents insightsEvents, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    return LaunderThrowable.await(pushEventsWithHTTPInfoAsync(insightsEvents, requestOptions));
  }

  /**
   * Sends a list of events to the Insights API. You can include up to 1,000 events in a single
   * request, but the request body must be smaller than 2&nbsp;MB.
   *
   * @param insightsEvents (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public EventsResponse pushEvents(@Nonnull InsightsEvents insightsEvents) throws FlapjackRuntimeException {
    return this.pushEvents(insightsEvents, null);
  }

  /**
   * Sends a list of events to the Insights API. You can include up to 1,000 events in a single
   * request, but the request body must be smaller than 2&nbsp;MB.
   *
   * @param insightsEvents (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public Response pushEventsWithHTTPInfo(@Nonnull InsightsEvents insightsEvents) throws FlapjackRuntimeException {
    return this.pushEventsWithHTTPInfo(insightsEvents, null);
  }

  /**
   * (asynchronously) Sends a list of events to the Insights API. You can include up to 1,000 events
   * in a single request, but the request body must be smaller than 2&nbsp;MB.
   *
   * @param insightsEvents (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<EventsResponse> pushEventsAsync(@Nonnull InsightsEvents insightsEvents, @Nullable RequestOptions requestOptions)
    throws FlapjackRuntimeException {
    Parameters.requireNonNull(insightsEvents, "Parameter `insightsEvents` is required when calling `pushEvents`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/events").setMethod("POST").setBody(insightsEvents).build();
    return executeAsync(request, requestOptions, new TypeReference<EventsResponse>() {});
  }

  /**
   * (asynchronously) Sends a list of events to the Insights API. You can include up to 1,000 events
   * in a single request, but the request body must be smaller than 2&nbsp;MB.
   *
   * @param insightsEvents (required)
   * @param requestOptions The requestOptions to send along with the query, they will be merged with
   *     the transporter requestOptions.
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> pushEventsWithHTTPInfoAsync(
    @Nonnull InsightsEvents insightsEvents,
    @Nullable RequestOptions requestOptions
  ) throws FlapjackRuntimeException {
    Parameters.requireNonNull(insightsEvents, "Parameter `insightsEvents` is required when calling `pushEvents`.");

    HttpRequest request = HttpRequest.builder().setPath("/1/events").setMethod("POST").setBody(insightsEvents).build();
    return executeAsync(request, requestOptions, new TypeReference<Response>() {});
  }

  /**
   * (asynchronously) Sends a list of events to the Insights API. You can include up to 1,000 events
   * in a single request, but the request body must be smaller than 2&nbsp;MB.
   *
   * @param insightsEvents (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<EventsResponse> pushEventsAsync(@Nonnull InsightsEvents insightsEvents) throws FlapjackRuntimeException {
    return this.pushEventsAsync(insightsEvents, null);
  }

  /**
   * (asynchronously) Sends a list of events to the Insights API. You can include up to 1,000 events
   * in a single request, but the request body must be smaller than 2&nbsp;MB.
   *
   * @param insightsEvents (required)
   * @throws FlapjackRuntimeException If it fails to process the API call
   */
  public CompletableFuture<Response> pushEventsWithHTTPInfoAsync(@Nonnull InsightsEvents insightsEvents) throws FlapjackRuntimeException {
    return this.pushEventsWithHTTPInfoAsync(insightsEvents, null);
  }
}
