// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public struct RecommendClientConfiguration: BaseConfiguration, Credentials {
    public let appID: String
    public var apiKey: String
    public var writeTimeout: TimeInterval
    public var readTimeout: TimeInterval
    public var logLevel: LogLevel
    public var defaultHeaders: [String: String]?
    public var hosts: [RetryableHost]
    public let compression: CompressionAlgorithm

    public init(
        appID: String,
        apiKey: String,
        writeTimeout: TimeInterval = 30,
        readTimeout: TimeInterval = 5,
        logLevel: LogLevel = DefaultConfiguration.default.logLevel,
        defaultHeaders: [String: String]? = DefaultConfiguration.default.defaultHeaders,
        hosts: [RetryableHost]? = nil,
        compression: CompressionAlgorithm = .none
    ) throws {
        guard !appID.isEmpty else {
            throw FlapjackError.invalidCredentials("appId")
        }

        guard !apiKey.isEmpty else {
            throw FlapjackError.invalidCredentials("apiKey")
        }

        self.appID = appID
        self.apiKey = apiKey
        self.writeTimeout = writeTimeout
        self.readTimeout = readTimeout
        self.logLevel = logLevel
        self.defaultHeaders = [
            "X-Algolia-Application-Id": appID,
            "X-Algolia-API-Key": apiKey,
            "Content-Type": "application/json",
        ].merging(defaultHeaders ?? [:]) { _, new in new }
        self.compression = compression

        UserAgentController.append(UserAgent(title: "Recommend", version: Version.current.description))

        guard let hosts else {
            func buildHost(_ components: (suffix: String, callType: RetryableHost.CallTypeSupport)) throws
            -> RetryableHost {
                guard let url = URL(string: "https://\(appID)\(components.suffix)") else {
                    throw FlapjackError.runtimeError("Malformed URL")
                }

                return RetryableHost(url: url, callType: components.callType)
            }

            let hosts = try [
                ("-dsn.flapjack.io", .read),
                (".flapjack.io", .write),
            ].map(buildHost)

            let commonHosts = try [
                ("-1.flapjack.io", .universal),
                ("-2.flapjack.io", .universal),
                ("-3.flapjack.io", .universal),
            ].map(buildHost).shuffled()

            self.hosts = hosts + commonHosts

            return
        }

        self.hosts = hosts
    }
}
