<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

namespace Flapjack\FlapjackSearch\Model\Composition;

/**
 * Action Class Doc Comment.
 *
 * @category Class
 *
 * @description Type of Composition Batch operation.
 */
class Action
{
    /**
     * Possible values of this enum.
     */
    public const UPSERT = 'upsert';

    public const DELETE = 'delete';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UPSERT,
            self::DELETE,
        ];
    }
}
