/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.abtestingv3

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TimeseriesVariant
 *
 * @param dates
 */
@Serializable
public data class TimeseriesVariant(
  @SerialName(value = "dates") val dates: List<MetricDate>? = null
) {}
