//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Search;

/// <summary>
/// Operation to perform on the index.
/// </summary>
/// <value>Operation to perform on the index.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<OperationType>))]
public enum OperationType
{
  /// <summary>
  /// Enum Move for value: move
  /// </summary>
  [JsonPropertyName("move")]
  Move = 1,

  /// <summary>
  /// Enum Copy for value: copy
  /// </summary>
  [JsonPropertyName("copy")]
  Copy = 2,
}
