//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Search;

/// <summary>
/// - `default`: perform a search query - `facet` [searches for facet values](https://www.flapjack.io/doc/guides/managing-results/refine-results/faceting/#search-for-facet-values).
/// </summary>
/// <value>- `default`: perform a search query - `facet` [searches for facet values](https://www.flapjack.io/doc/guides/managing-results/refine-results/faceting/#search-for-facet-values). </value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<SearchTypeFacet>))]
public enum SearchTypeFacet
{
  /// <summary>
  /// Enum Facet for value: facet
  /// </summary>
  [JsonPropertyName("facet")]
  Facet = 1,
}
