// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

package com.flapjackhq.model.ingestion;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;

/** HTTP method to be used for retrieving your data. */
public enum MethodType {
  GET("GET"),

  POST("POST");

  private final String value;

  MethodType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MethodType fromValue(String value) {
    for (MethodType b : MethodType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
