//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Ingestion;

/// <summary>
/// Credentials for authenticating with the Flapjack Insights API.
/// </summary>
public partial class AuthFlapjackInsightsPartial
{
  /// <summary>
  /// Initializes a new instance of the AuthFlapjackInsightsPartial class.
  /// </summary>
  public AuthFlapjackInsightsPartial() { }

  /// <summary>
  /// Flapjack application ID.
  /// </summary>
  /// <value>Flapjack application ID.</value>
  [JsonPropertyName("appID")]
  public string AppID { get; set; }

  /// <summary>
  /// Flapjack API key with the ACL: `search`. This field is `null` in the API response.
  /// </summary>
  /// <value>Flapjack API key with the ACL: `search`. This field is `null` in the API response. </value>
  [JsonPropertyName("apiKey")]
  public string ApiKey { get; set; }

  /// <summary>
  /// Returns the string presentation of the object
  /// </summary>
  /// <returns>String presentation of the object</returns>
  public override string ToString()
  {
    StringBuilder sb = new StringBuilder();
    sb.Append("class AuthFlapjackInsightsPartial {\n");
    sb.Append("  AppID: ").Append(AppID).Append("\n");
    sb.Append("  ApiKey: ").Append(ApiKey).Append("\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  /// <summary>
  /// Returns the JSON string presentation of the object
  /// </summary>
  /// <returns>JSON string presentation of the object</returns>
  public virtual string ToJson()
  {
    return JsonSerializer.Serialize(this, JsonConfig.Options);
  }

  /// <summary>
  /// Returns true if objects are equal
  /// </summary>
  /// <param name="obj">Object to be compared</param>
  /// <returns>Boolean</returns>
  public override bool Equals(object obj)
  {
    if (obj is not AuthFlapjackInsightsPartial input)
    {
      return false;
    }

    return (AppID == input.AppID || (AppID != null && AppID.Equals(input.AppID)))
      && (ApiKey == input.ApiKey || (ApiKey != null && ApiKey.Equals(input.ApiKey)));
  }

  /// <summary>
  /// Gets the hash code
  /// </summary>
  /// <returns>Hash code</returns>
  public override int GetHashCode()
  {
    unchecked // Overflow is fine, just wrap
    {
      int hashCode = 41;
      if (AppID != null)
      {
        hashCode = (hashCode * 59) + AppID.GetHashCode();
      }
      if (ApiKey != null)
      {
        hashCode = (hashCode * 59) + ApiKey.GetHashCode();
      }
      return hashCode;
    }
  }
}
