//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Ingestion;

/// <summary>
/// Destination type.  - `search`.   Data is stored in a Flapjack index.  - `insights`.   Data is recorded as user events in the Insights API.
/// </summary>
/// <value>Destination type.  - `search`.   Data is stored in a Flapjack index.  - `insights`.   Data is recorded as user events in the Insights API. </value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<DestinationType>))]
public enum DestinationType
{
  /// <summary>
  /// Enum Search for value: search
  /// </summary>
  [JsonPropertyName("search")]
  Search = 1,

  /// <summary>
  /// Enum Insights for value: insights
  /// </summary>
  [JsonPropertyName("insights")]
  Insights = 2,
}
