//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Ingestion;

/// <summary>
/// HTTP method to be used for retrieving your data.
/// </summary>
/// <value>HTTP method to be used for retrieving your data.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<MethodType>))]
public enum MethodType
{
  /// <summary>
  /// Enum GET for value: GET
  /// </summary>
  [JsonPropertyName("GET")]
  GET = 1,

  /// <summary>
  /// Enum POST for value: POST
  /// </summary>
  [JsonPropertyName("POST")]
  POST = 2,
}
