//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Ingestion;

/// <summary>
/// Task run status.
/// </summary>
/// <value>Task run status.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<RunStatus>))]
public enum RunStatus
{
  /// <summary>
  /// Enum Created for value: created
  /// </summary>
  [JsonPropertyName("created")]
  Created = 1,

  /// <summary>
  /// Enum Started for value: started
  /// </summary>
  [JsonPropertyName("started")]
  Started = 2,

  /// <summary>
  /// Enum Finished for value: finished
  /// </summary>
  [JsonPropertyName("finished")]
  Finished = 3,

  /// <summary>
  /// Enum Skipped for value: skipped
  /// </summary>
  [JsonPropertyName("skipped")]
  Skipped = 4,
}
