//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Ingestion;

/// <summary>
/// Task runs on a schedule.
/// </summary>
/// <value>Task runs on a schedule.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<ScheduleTriggerType>))]
public enum ScheduleTriggerType
{
  /// <summary>
  /// Enum Schedule for value: schedule
  /// </summary>
  [JsonPropertyName("schedule")]
  Schedule = 1,
}
