//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Ingestion;

/// <summary>
/// Task runs after receiving subscribed event.
/// </summary>
/// <value>Task runs after receiving subscribed event.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<SubscriptionTriggerType>))]
public enum SubscriptionTriggerType
{
  /// <summary>
  /// Enum Subscription for value: subscription
  /// </summary>
  [JsonPropertyName("subscription")]
  Subscription = 1,
}
