//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Ingestion;

/// <summary>
/// The type of transformation, which can be either 'code' or 'noCode'.
/// </summary>
/// <value>The type of transformation, which can be either 'code' or 'noCode'.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<TransformationType>))]
public enum TransformationType
{
  /// <summary>
  /// Enum Code for value: code
  /// </summary>
  [JsonPropertyName("code")]
  Code = 1,

  /// <summary>
  /// Enum NoCode for value: noCode
  /// </summary>
  [JsonPropertyName("noCode")]
  NoCode = 2,
}
