/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.recommend

import kotlinx.serialization.*

@Serializable
public enum class BooleanString(public val value: kotlin.String) : IgnorePlurals {

  @SerialName(value = "true") True("true"),
  @SerialName(value = "false") False("false");

  override fun toString(): kotlin.String = value
}
