/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * GetRecommendationsResponse
 *
 * @param results
 */
@Serializable
public data class GetRecommendationsResponse(
  @SerialName(value = "results") val results: List<RecommendationsResults>
) {}
