/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Recommend request body.
 *
 * @param requests Recommendation request with parameters depending on the requested model.
 */
@Serializable
public data class GetRecommendationsParams(

  /** Recommendation request with parameters depending on the requested model. */
  @SerialName(value = "requests") val requests: List<RecommendationsRequest>
) {}
