/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.recommend

import com.flapjackhq.client.exception.AlgoliaClientException
import com.flapjackhq.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * RecommendationsHit
 *
 * Implementations:
 * - [RecommendHit]
 * - [TrendingFacetHit]
 */
@Serializable(RecommendationsHitSerializer::class)
public sealed interface RecommendationsHit {
  @Serializable
  @JvmInline
  public value class TrendingFacetHitValue(public val value: TrendingFacetHit) : RecommendationsHit

  @Serializable
  @JvmInline
  public value class RecommendHitValue(public val value: RecommendHit) : RecommendationsHit

  public companion object {

    public fun of(value: TrendingFacetHit): RecommendationsHit = TrendingFacetHitValue(value)

    public fun of(value: RecommendHit): RecommendationsHit = RecommendHitValue(value)
  }
}

internal class RecommendationsHitSerializer :
  JsonContentPolymorphicSerializer<RecommendationsHit>(RecommendationsHit::class) {
  override fun selectDeserializer(
    element: JsonElement
  ): DeserializationStrategy<RecommendationsHit> {
    return when {
      element is JsonObject &&
        element.containsKey("facetName") &&
        element.containsKey("facetValue") -> TrendingFacetHit.serializer()
      element is JsonObject && element.containsKey("objectID") -> RecommendHit.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
