/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.recommend

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * [Redirect results to a
 * URL](https://www.flapjack.io/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/redirects),
 * this this parameter is for internal use only.
 *
 * @param index
 */
@Serializable
public data class Redirect(
  @SerialName(value = "index") val index: List<RedirectRuleIndexMetadata>? = null
) {}
