/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.abtesting

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * A/B test filter effects resulting from configuration settings.
 *
 * @param outliers
 * @param emptySearch
 */
@Serializable
public data class FilterEffects(
  @SerialName(value = "outliers") val outliers: OutliersFilter? = null,
  @SerialName(value = "emptySearch") val emptySearch: EmptySearchFilter? = null,
) {}
