// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

/// Task status, `published` if the task is completed, `notPublished` otherwise.
public enum CompositionTaskStatus: String, Codable, CaseIterable {
    case published
    case notPublished
}

extension CompositionTaskStatus: Hashable {}
