<?php

// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

namespace Flapjack\FlapjackSearch\Model\Ingestion;

/**
 * StreamingTriggerType Class Doc Comment.
 *
 * @category Class
 *
 * @description Task runs continuously.
 */
class StreamingTriggerType
{
    /**
     * Possible values of this enum.
     */
    public const STREAMING = 'streaming';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STREAMING,
        ];
    }
}
