require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.test_files = FileList['tests/*_test.rb']
  t.verbose = true
end

task(:default) { system 'rake --tasks' }

