// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
package ingestion

import (
	"github.com/flapjackhq/flapjack-search-go/v4/flapjack/transport"
)

var allowedRegions = [...]string{"eu", "us"}

type Region string

const (
	EU Region = "eu"
	US Region = "us"
)

// IngestionConfiguration stores the configuration of the API client.
type IngestionConfiguration struct {
	transport.Configuration

	Region Region
}
