/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.personalization

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * FacetsScoring
 *
 * @param score Event score.
 * @param facetName Facet attribute name.
 */
@Serializable
public data class FacetsScoring(

  /** Event score. */
  @SerialName(value = "score") val score: Int,

  /** Facet attribute name. */
  @SerialName(value = "facetName") val facetName: String,
) {}
