//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Flapjack.Search.Http;
using Flapjack.Search.Models.Monitoring;
using Flapjack.Search.Transport;
using Flapjack.Search.Utils;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Flapjack.Search.Clients;

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface IMonitoringClient
{
  /// <summary>
  /// This method lets you send requests to the Flapjack REST API.
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of object</returns>
  Task<object> CustomDeleteAsync(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API. (Synchronous version)
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>object</returns>
  object CustomDelete(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API.
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of object</returns>
  Task<FlapjackHttpResponse> CustomDeleteWithHTTPInfoAsync(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API. (Synchronous version)
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>object</returns>
  FlapjackHttpResponse CustomDeleteWithHTTPInfo(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API.
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of object</returns>
  Task<object> CustomGetAsync(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API. (Synchronous version)
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>object</returns>
  object CustomGet(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API.
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of object</returns>
  Task<FlapjackHttpResponse> CustomGetWithHTTPInfoAsync(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API. (Synchronous version)
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>object</returns>
  FlapjackHttpResponse CustomGetWithHTTPInfo(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API.
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="body">Parameters to send with the custom request. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of object</returns>
  Task<object> CustomPostAsync(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API. (Synchronous version)
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="body">Parameters to send with the custom request. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>object</returns>
  object CustomPost(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API.
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="body">Parameters to send with the custom request. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of object</returns>
  Task<FlapjackHttpResponse> CustomPostWithHTTPInfoAsync(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API. (Synchronous version)
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="body">Parameters to send with the custom request. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>object</returns>
  FlapjackHttpResponse CustomPostWithHTTPInfo(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API.
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="body">Parameters to send with the custom request. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of object</returns>
  Task<object> CustomPutAsync(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API. (Synchronous version)
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="body">Parameters to send with the custom request. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>object</returns>
  object CustomPut(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API.
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="body">Parameters to send with the custom request. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of object</returns>
  Task<FlapjackHttpResponse> CustomPutWithHTTPInfoAsync(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// This method lets you send requests to the Flapjack REST API. (Synchronous version)
  /// </summary>
  /// <param name="path">Path of the endpoint, for example `1/newFeature`.</param>
  /// <param name="parameters">Query parameters to apply to the current query. (optional)</param>
  /// <param name="body">Parameters to send with the custom request. (optional)</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>object</returns>
  FlapjackHttpResponse CustomPutWithHTTPInfo(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves known incidents for the selected clusters.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of IncidentsResponse</returns>
  Task<IncidentsResponse> GetClusterIncidentsAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves known incidents for the selected clusters. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>IncidentsResponse</returns>
  IncidentsResponse GetClusterIncidents(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves known incidents for the selected clusters.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of IncidentsResponse</returns>
  Task<FlapjackHttpResponse> GetClusterIncidentsWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves known incidents for the selected clusters. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>IncidentsResponse</returns>
  FlapjackHttpResponse GetClusterIncidentsWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the status of selected clusters.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of StatusResponse</returns>
  Task<StatusResponse> GetClusterStatusAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the status of selected clusters. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>StatusResponse</returns>
  StatusResponse GetClusterStatus(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the status of selected clusters.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of StatusResponse</returns>
  Task<FlapjackHttpResponse> GetClusterStatusWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the status of selected clusters. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>StatusResponse</returns>
  FlapjackHttpResponse GetClusterStatusWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves known incidents for all clusters.
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of IncidentsResponse</returns>
  Task<IncidentsResponse> GetIncidentsAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves known incidents for all clusters. (Synchronous version)
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>IncidentsResponse</returns>
  IncidentsResponse GetIncidents(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves known incidents for all clusters.
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of IncidentsResponse</returns>
  Task<FlapjackHttpResponse> GetIncidentsWithHTTPInfoAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves known incidents for all clusters. (Synchronous version)
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>IncidentsResponse</returns>
  FlapjackHttpResponse GetIncidentsWithHTTPInfo(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves average times for indexing operations for selected clusters.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of IndexingTimeResponse</returns>
  Task<IndexingTimeResponse> GetIndexingTimeAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves average times for indexing operations for selected clusters. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>IndexingTimeResponse</returns>
  IndexingTimeResponse GetIndexingTime(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves average times for indexing operations for selected clusters.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of IndexingTimeResponse</returns>
  Task<FlapjackHttpResponse> GetIndexingTimeWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves average times for indexing operations for selected clusters. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>IndexingTimeResponse</returns>
  FlapjackHttpResponse GetIndexingTimeWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the average latency for search requests for selected clusters.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of LatencyResponse</returns>
  Task<LatencyResponse> GetLatencyAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the average latency for search requests for selected clusters. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>LatencyResponse</returns>
  LatencyResponse GetLatency(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the average latency for search requests for selected clusters.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of LatencyResponse</returns>
  Task<FlapjackHttpResponse> GetLatencyWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the average latency for search requests for selected clusters. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>LatencyResponse</returns>
  FlapjackHttpResponse GetLatencyWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves metrics related to your Flapjack infrastructure, aggregated over a selected time window.  Access to this API is available as part of the [Premium or Elevate plans](https://www.flapjack.io/pricing). You must authenticate requests with the `x-algolia-application-id` and `x-algolia-api-key` headers (using the Monitoring API key).
  /// </summary>
  /// <param name="metric">Metric to report.  For more information about the individual metrics, see the description of the API response. To include all metrics, use `*`. </param>
  /// <param name="period">Period over which to aggregate the metrics:  - `minute`. Aggregate the last minute. 1 data point per 10 seconds. - `hour`. Aggregate the last hour. 1 data point per minute. - `day`. Aggregate the last day. 1 data point per 10 minutes. - `week`. Aggregate the last week. 1 data point per hour. - `month`. Aggregate the last month. 1 data point per day. </param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of InfrastructureResponse</returns>
  Task<InfrastructureResponse> GetMetricsAsync(
    Metric metric,
    Period period,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves metrics related to your Flapjack infrastructure, aggregated over a selected time window.  Access to this API is available as part of the [Premium or Elevate plans](https://www.flapjack.io/pricing). You must authenticate requests with the `x-algolia-application-id` and `x-algolia-api-key` headers (using the Monitoring API key).  (Synchronous version)
  /// </summary>
  /// <param name="metric">Metric to report.  For more information about the individual metrics, see the description of the API response. To include all metrics, use `*`. </param>
  /// <param name="period">Period over which to aggregate the metrics:  - `minute`. Aggregate the last minute. 1 data point per 10 seconds. - `hour`. Aggregate the last hour. 1 data point per minute. - `day`. Aggregate the last day. 1 data point per 10 minutes. - `week`. Aggregate the last week. 1 data point per hour. - `month`. Aggregate the last month. 1 data point per day. </param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>InfrastructureResponse</returns>
  InfrastructureResponse GetMetrics(
    Metric metric,
    Period period,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves metrics related to your Flapjack infrastructure, aggregated over a selected time window.  Access to this API is available as part of the [Premium or Elevate plans](https://www.flapjack.io/pricing). You must authenticate requests with the `x-algolia-application-id` and `x-algolia-api-key` headers (using the Monitoring API key).
  /// </summary>
  /// <param name="metric">Metric to report.  For more information about the individual metrics, see the description of the API response. To include all metrics, use `*`. </param>
  /// <param name="period">Period over which to aggregate the metrics:  - `minute`. Aggregate the last minute. 1 data point per 10 seconds. - `hour`. Aggregate the last hour. 1 data point per minute. - `day`. Aggregate the last day. 1 data point per 10 minutes. - `week`. Aggregate the last week. 1 data point per hour. - `month`. Aggregate the last month. 1 data point per day. </param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of InfrastructureResponse</returns>
  Task<FlapjackHttpResponse> GetMetricsWithHTTPInfoAsync(
    Metric metric,
    Period period,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves metrics related to your Flapjack infrastructure, aggregated over a selected time window.  Access to this API is available as part of the [Premium or Elevate plans](https://www.flapjack.io/pricing). You must authenticate requests with the `x-algolia-application-id` and `x-algolia-api-key` headers (using the Monitoring API key).  (Synchronous version)
  /// </summary>
  /// <param name="metric">Metric to report.  For more information about the individual metrics, see the description of the API response. To include all metrics, use `*`. </param>
  /// <param name="period">Period over which to aggregate the metrics:  - `minute`. Aggregate the last minute. 1 data point per 10 seconds. - `hour`. Aggregate the last hour. 1 data point per minute. - `day`. Aggregate the last day. 1 data point per 10 minutes. - `week`. Aggregate the last week. 1 data point per hour. - `month`. Aggregate the last month. 1 data point per day. </param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>InfrastructureResponse</returns>
  FlapjackHttpResponse GetMetricsWithHTTPInfo(
    Metric metric,
    Period period,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Test whether clusters are reachable or not.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of Dictionary{string, Dictionary{string, bool}}</returns>
  Task<Dictionary<string, Dictionary<string, bool>>> GetReachabilityAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Test whether clusters are reachable or not. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Dictionary{string, Dictionary{string, bool}}</returns>
  Dictionary<string, Dictionary<string, bool>> GetReachability(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Test whether clusters are reachable or not.
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of Dictionary{string, Dictionary{string, bool}}</returns>
  Task<FlapjackHttpResponse> GetReachabilityWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Test whether clusters are reachable or not. (Synchronous version)
  /// </summary>
  /// <param name="clusters">Subset of clusters, separated by commas.</param>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Dictionary{string, Dictionary{string, bool}}</returns>
  FlapjackHttpResponse GetReachabilityWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the servers that belong to clusters.  The response depends on whether you authenticate your API request:  - With authentication, the response lists the servers assigned to your Flapjack application's cluster.  - Without authentication, the response lists the servers for all Flapjack clusters.
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of InventoryResponse</returns>
  Task<InventoryResponse> GetServersAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the servers that belong to clusters.  The response depends on whether you authenticate your API request:  - With authentication, the response lists the servers assigned to your Flapjack application's cluster.  - Without authentication, the response lists the servers for all Flapjack clusters.  (Synchronous version)
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>InventoryResponse</returns>
  InventoryResponse GetServers(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the servers that belong to clusters.  The response depends on whether you authenticate your API request:  - With authentication, the response lists the servers assigned to your Flapjack application's cluster.  - Without authentication, the response lists the servers for all Flapjack clusters.
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of InventoryResponse</returns>
  Task<FlapjackHttpResponse> GetServersWithHTTPInfoAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the servers that belong to clusters.  The response depends on whether you authenticate your API request:  - With authentication, the response lists the servers assigned to your Flapjack application's cluster.  - Without authentication, the response lists the servers for all Flapjack clusters.  (Synchronous version)
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>InventoryResponse</returns>
  FlapjackHttpResponse GetServersWithHTTPInfo(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the status of all Flapjack clusters and instances.
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of StatusResponse</returns>
  Task<StatusResponse> GetStatusAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the status of all Flapjack clusters and instances. (Synchronous version)
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>StatusResponse</returns>
  StatusResponse GetStatus(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the status of all Flapjack clusters and instances.
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>Task of StatusResponse</returns>
  Task<FlapjackHttpResponse> GetStatusWithHTTPInfoAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );

  /// <summary>
  /// Retrieves the status of all Flapjack clusters and instances. (Synchronous version)
  /// </summary>
  /// <param name="options">Add extra http header or query parameters to Flapjack.</param>
  /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
  /// <exception cref="ArgumentException">Thrown when arguments are not correct</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackApiException">Thrown when the API call was rejected by Flapjack</exception>
  /// <exception cref="Flapjack.Search.Exceptions.FlapjackUnreachableHostException">Thrown when the client failed to call the endpoint</exception>
  /// <returns>StatusResponse</returns>
  FlapjackHttpResponse GetStatusWithHTTPInfo(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  );
}

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public partial class MonitoringClient : IMonitoringClient
{
  internal HttpTransport _transport;
  private readonly ILogger<MonitoringClient> _logger;

  /// <summary>
  /// Create a new Monitoring client for the given appID and apiKey.
  /// </summary>
  /// <param name="applicationId">Your application</param>
  /// <param name="apiKey">Your API key</param>
  /// <param name="loggerFactory">Logger factory</param>
  public MonitoringClient(string applicationId, string apiKey, ILoggerFactory loggerFactory = null)
    : this(
      new MonitoringConfig(applicationId, apiKey),
      new FlapjackHttpRequester(loggerFactory),
      loggerFactory
    )
  { }

  /// <summary>
  /// Initialize a client with custom config
  /// </summary>
  /// <param name="config">Flapjack configuration</param>
  /// <param name="loggerFactory">Logger factory</param>
  public MonitoringClient(MonitoringConfig config, ILoggerFactory loggerFactory = null)
    : this(config, new FlapjackHttpRequester(loggerFactory), loggerFactory) { }

  /// <summary>
  /// Initialize the client with custom config and custom Requester
  /// </summary>
  /// <param name="config">Flapjack Config</param>
  /// <param name="httpRequester">Your Http requester implementation of <see cref="IHttpRequester"/></param>
  /// <param name="loggerFactory">Logger factory</param>
  public MonitoringClient(
    MonitoringConfig config,
    IHttpRequester httpRequester,
    ILoggerFactory loggerFactory = null
  )
  {
    if (httpRequester == null)
    {
      throw new ArgumentException("An httpRequester is required");
    }
    if (config == null)
    {
      throw new ArgumentException("A config is required");
    }
    if (string.IsNullOrWhiteSpace(config.AppId))
    {
      throw new ArgumentException("`AppId` is missing.");
    }
    if (string.IsNullOrWhiteSpace(config.ApiKey))
    {
      throw new ArgumentException("`ApiKey` is missing.");
    }

    var factory = loggerFactory ?? NullLoggerFactory.Instance;
    _transport = new HttpTransport(config, httpRequester, factory);
    _logger = factory.CreateLogger<MonitoringClient>();

    if (_logger.IsEnabled(Microsoft.Extensions.Logging.LogLevel.Information))
    {
      _logger.LogInformation("Flapjack Monitoring client is initialized.");
    }
  }

  /// <summary>
  /// Helper to switch the API key sent with each request
  /// </summary>
  /// <param name="apiKey">Your new API Key</param>
  /// <returns></returns>
  public void SetClientApiKey(string apiKey)
  {
    _transport._flapjackConfig.SetClientApiKey(apiKey);
  }

  /// <inheritdoc />
  public async Task<object> CustomDeleteAsync(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (path == null)
      throw new ArgumentException("Parameter `path` is required when calling `CustomDelete`.");

    var requestOptions = new InternalRequestOptions(options);
    requestOptions.CustomPathParameters.Add("path", QueryStringHelper.ParameterToString(path));

    requestOptions.AddCustomQueryParameters(parameters);
    return await _transport
      .ExecuteRequestAsync<object>(
        new HttpMethod("DELETE"),
        "/{path}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public object CustomDelete(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => CustomDeleteAsync(path, parameters, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> CustomDeleteWithHTTPInfoAsync(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (path == null)
      throw new ArgumentException("Parameter `path` is required when calling `CustomDelete`.");

    var requestOptions = new InternalRequestOptions(options);
    requestOptions.CustomPathParameters.Add("path", QueryStringHelper.ParameterToString(path));

    requestOptions.AddCustomQueryParameters(parameters);
    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("DELETE"),
        "/{path}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse CustomDeleteWithHTTPInfo(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      CustomDeleteWithHTTPInfoAsync(path, parameters, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<object> CustomGetAsync(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (path == null)
      throw new ArgumentException("Parameter `path` is required when calling `CustomGet`.");

    var requestOptions = new InternalRequestOptions(options);
    requestOptions.CustomPathParameters.Add("path", QueryStringHelper.ParameterToString(path));

    requestOptions.AddCustomQueryParameters(parameters);
    return await _transport
      .ExecuteRequestAsync<object>(
        new HttpMethod("GET"),
        "/{path}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public object CustomGet(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => CustomGetAsync(path, parameters, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> CustomGetWithHTTPInfoAsync(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (path == null)
      throw new ArgumentException("Parameter `path` is required when calling `CustomGet`.");

    var requestOptions = new InternalRequestOptions(options);
    requestOptions.CustomPathParameters.Add("path", QueryStringHelper.ParameterToString(path));

    requestOptions.AddCustomQueryParameters(parameters);
    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/{path}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse CustomGetWithHTTPInfo(
    string path,
    Dictionary<string, object> parameters = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      CustomGetWithHTTPInfoAsync(path, parameters, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<object> CustomPostAsync(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (path == null)
      throw new ArgumentException("Parameter `path` is required when calling `CustomPost`.");

    var requestOptions = new InternalRequestOptions(options);
    requestOptions.CustomPathParameters.Add("path", QueryStringHelper.ParameterToString(path));

    requestOptions.AddCustomQueryParameters(parameters);
    requestOptions.Data = body;
    return await _transport
      .ExecuteRequestAsync<object>(
        new HttpMethod("POST"),
        "/{path}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public object CustomPost(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() => CustomPostAsync(path, parameters, body, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> CustomPostWithHTTPInfoAsync(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (path == null)
      throw new ArgumentException("Parameter `path` is required when calling `CustomPost`.");

    var requestOptions = new InternalRequestOptions(options);
    requestOptions.CustomPathParameters.Add("path", QueryStringHelper.ParameterToString(path));

    requestOptions.AddCustomQueryParameters(parameters);
    requestOptions.Data = body;
    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("POST"),
        "/{path}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse CustomPostWithHTTPInfo(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      CustomPostWithHTTPInfoAsync(path, parameters, body, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<object> CustomPutAsync(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (path == null)
      throw new ArgumentException("Parameter `path` is required when calling `CustomPut`.");

    var requestOptions = new InternalRequestOptions(options);
    requestOptions.CustomPathParameters.Add("path", QueryStringHelper.ParameterToString(path));

    requestOptions.AddCustomQueryParameters(parameters);
    requestOptions.Data = body;
    return await _transport
      .ExecuteRequestAsync<object>(
        new HttpMethod("PUT"),
        "/{path}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public object CustomPut(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() => CustomPutAsync(path, parameters, body, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> CustomPutWithHTTPInfoAsync(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (path == null)
      throw new ArgumentException("Parameter `path` is required when calling `CustomPut`.");

    var requestOptions = new InternalRequestOptions(options);
    requestOptions.CustomPathParameters.Add("path", QueryStringHelper.ParameterToString(path));

    requestOptions.AddCustomQueryParameters(parameters);
    requestOptions.Data = body;
    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("PUT"),
        "/{path}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse CustomPutWithHTTPInfo(
    string path,
    Dictionary<string, object> parameters = default,
    object body = default,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      CustomPutWithHTTPInfoAsync(path, parameters, body, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<IncidentsResponse> GetClusterIncidentsAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException(
        "Parameter `clusters` is required when calling `GetClusterIncidents`."
      );

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<IncidentsResponse>(
        new HttpMethod("GET"),
        "/1/incidents/{clusters}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public IncidentsResponse GetClusterIncidents(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetClusterIncidentsAsync(clusters, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetClusterIncidentsWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException(
        "Parameter `clusters` is required when calling `GetClusterIncidents`."
      );

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/incidents/{clusters}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetClusterIncidentsWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      GetClusterIncidentsWithHTTPInfoAsync(clusters, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<StatusResponse> GetClusterStatusAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException(
        "Parameter `clusters` is required when calling `GetClusterStatus`."
      );

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<StatusResponse>(
        new HttpMethod("GET"),
        "/1/status/{clusters}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public StatusResponse GetClusterStatus(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetClusterStatusAsync(clusters, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetClusterStatusWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException(
        "Parameter `clusters` is required when calling `GetClusterStatus`."
      );

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/status/{clusters}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetClusterStatusWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      GetClusterStatusWithHTTPInfoAsync(clusters, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<IncidentsResponse> GetIncidentsAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    var requestOptions = new InternalRequestOptions(options);

    return await _transport
      .ExecuteRequestAsync<IncidentsResponse>(
        new HttpMethod("GET"),
        "/1/incidents",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public IncidentsResponse GetIncidents(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetIncidentsAsync(options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetIncidentsWithHTTPInfoAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    var requestOptions = new InternalRequestOptions(options);

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/incidents",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetIncidentsWithHTTPInfo(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetIncidentsWithHTTPInfoAsync(options, cancellationToken));

  /// <inheritdoc />
  public async Task<IndexingTimeResponse> GetIndexingTimeAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException(
        "Parameter `clusters` is required when calling `GetIndexingTime`."
      );

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<IndexingTimeResponse>(
        new HttpMethod("GET"),
        "/1/indexing/{clusters}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public IndexingTimeResponse GetIndexingTime(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetIndexingTimeAsync(clusters, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetIndexingTimeWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException(
        "Parameter `clusters` is required when calling `GetIndexingTime`."
      );

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/indexing/{clusters}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetIndexingTimeWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      GetIndexingTimeWithHTTPInfoAsync(clusters, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<LatencyResponse> GetLatencyAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException("Parameter `clusters` is required when calling `GetLatency`.");

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<LatencyResponse>(
        new HttpMethod("GET"),
        "/1/latency/{clusters}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public LatencyResponse GetLatency(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetLatencyAsync(clusters, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetLatencyWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException("Parameter `clusters` is required when calling `GetLatency`.");

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/latency/{clusters}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetLatencyWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetLatencyWithHTTPInfoAsync(clusters, options, cancellationToken));

  /// <inheritdoc />
  public async Task<InfrastructureResponse> GetMetricsAsync(
    Metric metric,
    Period period,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("metric", QueryStringHelper.ParameterToString(metric));
    requestOptions.PathParameters.Add("period", QueryStringHelper.ParameterToString(period));

    return await _transport
      .ExecuteRequestAsync<InfrastructureResponse>(
        new HttpMethod("GET"),
        "/1/infrastructure/{metric}/period/{period}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public InfrastructureResponse GetMetrics(
    Metric metric,
    Period period,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetMetricsAsync(metric, period, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetMetricsWithHTTPInfoAsync(
    Metric metric,
    Period period,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("metric", QueryStringHelper.ParameterToString(metric));
    requestOptions.PathParameters.Add("period", QueryStringHelper.ParameterToString(period));

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/infrastructure/{metric}/period/{period}",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetMetricsWithHTTPInfo(
    Metric metric,
    Period period,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      GetMetricsWithHTTPInfoAsync(metric, period, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<Dictionary<string, Dictionary<string, bool>>> GetReachabilityAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException(
        "Parameter `clusters` is required when calling `GetReachability`."
      );

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<Dictionary<string, Dictionary<string, bool>>>(
        new HttpMethod("GET"),
        "/1/reachability/{clusters}/probes",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public Dictionary<string, Dictionary<string, bool>> GetReachability(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetReachabilityAsync(clusters, options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetReachabilityWithHTTPInfoAsync(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    if (clusters == null)
      throw new ArgumentException(
        "Parameter `clusters` is required when calling `GetReachability`."
      );

    var requestOptions = new InternalRequestOptions(options);

    requestOptions.PathParameters.Add("clusters", QueryStringHelper.ParameterToString(clusters));

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/reachability/{clusters}/probes",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetReachabilityWithHTTPInfo(
    string clusters,
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) =>
    AsyncHelper.RunSync(() =>
      GetReachabilityWithHTTPInfoAsync(clusters, options, cancellationToken)
    );

  /// <inheritdoc />
  public async Task<InventoryResponse> GetServersAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    var requestOptions = new InternalRequestOptions(options);

    return await _transport
      .ExecuteRequestAsync<InventoryResponse>(
        new HttpMethod("GET"),
        "/1/inventory/servers",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public InventoryResponse GetServers(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetServersAsync(options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetServersWithHTTPInfoAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    var requestOptions = new InternalRequestOptions(options);

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/inventory/servers",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetServersWithHTTPInfo(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetServersWithHTTPInfoAsync(options, cancellationToken));

  /// <inheritdoc />
  public async Task<StatusResponse> GetStatusAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    var requestOptions = new InternalRequestOptions(options);

    return await _transport
      .ExecuteRequestAsync<StatusResponse>(
        new HttpMethod("GET"),
        "/1/status",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public StatusResponse GetStatus(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetStatusAsync(options, cancellationToken));

  /// <inheritdoc />
  public async Task<FlapjackHttpResponse> GetStatusWithHTTPInfoAsync(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  )
  {
    var requestOptions = new InternalRequestOptions(options);

    return await _transport
      .ExecuteRequestAsync<FlapjackHttpResponse>(
        new HttpMethod("GET"),
        "/1/status",
        requestOptions,
        cancellationToken
      )
      .ConfigureAwait(false);
  }

  /// <inheritdoc />
  public FlapjackHttpResponse GetStatusWithHTTPInfo(
    RequestOptions options = null,
    CancellationToken cancellationToken = default
  ) => AsyncHelper.RunSync(() => GetStatusWithHTTPInfoAsync(options, cancellationToken));
}
