/*
 * Flapjack Monitoring API
 *
   * ## Base URLs  Base URL for the Monitoring API:  - `https://status.flapjack.io`  **All requests must use HTTPS.**  ## Availability and authentication  Access to the Infrastructure endpoints is available as part of the [Premium or Elevate plans](https://www.flapjack.io/pricing).  To authenticate requests to the Infrastructure endpoints, add these headers:  - `x-algolia-application-id`. Your Flapjack application ID. - `x-algolia-api-key`. Your Monitoring API key.  You can find your application ID and API key in the [Algolia dashboard](https://dashboard.flapjack.io/account/api-keys).  Other endpoints don't require authentication.  ## Response status and errors  The Monitoring API returns JSON responses. Since JSON doesn't guarantee any specific ordering, don't rely on the order of attributes in the API response.  Successful responses return `2xx` statuses. Client errors return `4xx` statuses. Server errors return `5xx` statuses. Error responses have a `message` property with more information.  ## Version  The current version of the Monitoring API is version 1, indicated by the `/1/` in each endpoint's URL.
 *
   * The version of the OpenAPI document: 1.0.0
   * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using Flapjack.Search.Models.Common;
using Flapjack.Search.Transport;
using Flapjack.Search.Utils;

namespace Flapjack.Search.Clients;

/// <summary>
/// Monitoring client configuration
/// </summary>
public sealed class MonitoringConfig : FlapjackConfig
{
  /// <summary>
  /// The configuration of the Monitoring client
  /// A client should have it's own configuration ie on configuration per client instance
  /// </summary>
  /// <param name="appId">Your application ID</param>
  /// <param name="apiKey">Your API Key</param>
  public MonitoringConfig(string appId, string apiKey)
    : base(appId, apiKey, "Monitoring", "7.37.1")
  {
    DefaultHosts = GetDefaultHosts();
    Compression = CompressionType.None;
    ReadTimeout = TimeSpan.FromMilliseconds(5000);
    WriteTimeout = TimeSpan.FromMilliseconds(30000);
    ConnectTimeout = TimeSpan.FromMilliseconds(2000);
  }

  private static List<StatefulHost> GetDefaultHosts()
  {
    return new List<StatefulHost>
    {
      new()
      {
        Url = "status.flapjack.io",
        Up = true,
        LastUse = DateTime.UtcNow,
        Accept = CallType.Read | CallType.Write,
      },
    };
  }
}
