/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * GetSearchesNoClicksResponse
 *
 * @param searches Searches without any clicks.
 */
@Serializable
public data class GetSearchesNoClicksResponse(

  /** Searches without any clicks. */
  @SerialName(value = "searches") val searches: List<DailySearchesNoClicks>
) {}
