/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * GetStatusResponse
 *
 * @param updatedAt Date and time when the object was updated, in RFC 3339 format.
 */
@Serializable
public data class GetStatusResponse(

  /** Date and time when the object was updated, in RFC 3339 format. */
  @SerialName(value = "updatedAt") val updatedAt: String
) {}
