/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * GetTopFilterForAttributeResponse
 *
 * @param values Filter values for an attribute.
 */
@Serializable
public data class GetTopFilterForAttributeResponse(

  /** Filter values for an attribute. */
  @SerialName(value = "values") val values: List<GetTopFilterForAttribute>
) {}
