/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TopHitsResponseWithRevenueAnalytics
 *
 * @param hits Most frequent search results with click, conversion, and revenue metrics.
 */
@Serializable
public data class TopHitsResponseWithRevenueAnalytics(

  /** Most frequent search results with click, conversion, and revenue metrics. */
  @SerialName(value = "hits") val hits: List<TopHitWithRevenueAnalytics>
) : GetTopHitsResponse {}
