/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TopHitsResponseWithAnalytics
 *
 * @param hits Most frequent search results with click and conversion metrics.
 */
@Serializable
public data class TopHitsResponseWithAnalytics(

  /** Most frequent search results with click and conversion metrics. */
  @SerialName(value = "hits") val hits: List<TopHitWithAnalytics>
) : GetTopHitsResponse {}
