/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TopSearchesResponseWithRevenueAnalytics
 *
 * @param searches Most popular searches, including their click and revenue metrics.
 */
@Serializable
public data class TopSearchesResponseWithRevenueAnalytics(

  /** Most popular searches, including their click and revenue metrics. */
  @SerialName(value = "searches") val searches: List<TopSearchWithRevenueAnalytics>
) : GetTopSearchesResponse {}
