/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.analytics

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TopSearchesResponseWithAnalytics
 *
 * @param searches Most popular searches and their associated click and conversion metrics.
 */
@Serializable
public data class TopSearchesResponseWithAnalytics(

  /** Most popular searches and their associated click and conversion metrics. */
  @SerialName(value = "searches") val searches: List<TopSearchWithAnalytics>
) : GetTopSearchesResponse {}
