/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*

@Serializable
public enum class AlternativesAsExact(public val value: kotlin.String) {

  @SerialName(value = "ignorePlurals") IgnorePlurals("ignorePlurals"),
  @SerialName(value = "singleWordSynonym") SingleWordSynonym("singleWordSynonym"),
  @SerialName(value = "multiWordsSynonym") MultiWordsSynonym("multiWordsSynonym"),
  @SerialName(value = "ignoreConjugations") IgnoreConjugations("ignoreConjugations");

  override fun toString(): kotlin.String = value
}
