/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * URL for an image to show inside a banner.
 *
 * @param url
 */
@Serializable
public data class BannerImageUrl(@SerialName(value = "url") val url: String? = null) {}
