/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Object ID of the record to hide.
 *
 * @param objectID Unique record identifier.
 */
@Serializable
public data class ConsequenceHide(

  /** Unique record identifier. */
  @SerialName(value = "objectID") val objectID: String
) {}
