/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*

/** Whether a dictionary entry is active. */
@Serializable
public enum class DictionaryEntryState(public val value: kotlin.String) {

  @SerialName(value = "enabled") Enabled("enabled"),
  @SerialName(value = "disabled") Disabled("disabled");

  override fun toString(): kotlin.String = value
}
