/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import com.flapjackhq.client.exception.AlgoliaClientException
import com.flapjackhq.client.extensions.internal.*
import kotlin.jvm.JvmInline
import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * Determines how many records of a group are included in the search results. Records with the same
 * value for the `attributeForDistinct` attribute are considered a group. The `distinct` setting
 * controls how many members of the group are returned. This is useful for
 * [deduplication and grouping](https://www.flapjack.io/doc/guides/managing-results/refine-results/grouping/#introducing-algolias-distinct-feature).
 * The `distinct` setting is ignored if `attributeForDistinct` is not set.
 *
 * Implementations:
 * - [Boolean] - *[Distinct.of]*
 * - [Int] - *[Distinct.of]*
 */
@Serializable(DistinctSerializer::class)
public sealed interface Distinct {
  @Serializable @JvmInline public value class IntValue(public val value: Int) : Distinct

  @Serializable @JvmInline public value class BooleanValue(public val value: Boolean) : Distinct

  public companion object {

    public fun of(value: Int): Distinct = IntValue(value)

    public fun of(value: Boolean): Distinct = BooleanValue(value)
  }
}

internal class DistinctSerializer : JsonContentPolymorphicSerializer<Distinct>(Distinct::class) {
  override fun selectDeserializer(element: JsonElement): DeserializationStrategy<Distinct> {
    return when {
      element.isInt -> Distinct.IntValue.serializer()
      element.isBoolean -> Distinct.BooleanValue.serializer()
      else -> throw AlgoliaClientException("Failed to deserialize json element: $element")
    }
  }
}
