/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * GetLogsResponse
 *
 * @param logs
 */
@Serializable public data class GetLogsResponse(@SerialName(value = "logs") val logs: List<Log>) {}
