/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * User ID data.
 *
 * @param userIDs User IDs.
 */
@Serializable
public data class ListUserIdsResponse(

  /** User IDs. */
  @SerialName(value = "userIDs") val userIDs: List<UserId>
) {}
