/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * MultipleBatchResponse
 *
 * @param taskID Task IDs. One for each index.
 * @param objectIDs Unique record identifiers.
 */
@Serializable
public data class MultipleBatchResponse(

  /** Task IDs. One for each index. */
  @SerialName(value = "taskID") val taskID: Map<kotlin.String, Long>,

  /** Unique record identifiers. */
  @SerialName(value = "objectIDs") val objectIDs: List<String>,
) {}
