/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * ReplaceAllObjectsWithTransformationResponse
 *
 * @param copyOperationResponse
 * @param watchResponses The response of the `push` request(s).
 * @param moveOperationResponse
 */
@Serializable
public data class ReplaceAllObjectsWithTransformationResponse(
  @SerialName(value = "copyOperationResponse") val copyOperationResponse: UpdatedAtResponse,

  /** The response of the `push` request(s). */
  @SerialName(value = "watchResponses") val watchResponses: List<WatchResponse>,
  @SerialName(value = "moveOperationResponse") val moveOperationResponse: UpdatedAtResponse,
) {}
