/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Search parameters as query string.
 *
 * @param params Search parameters as a URL-encoded query string.
 */
@Serializable
public data class SearchParamsString(

  /** Search parameters as a URL-encoded query string. */
  @SerialName(value = "params") val params: String? = null
) : SearchParams, BrowseParams {}
