/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * UpdateApiKeyResponse
 *
 * @param key API key.
 * @param updatedAt Date and time when the object was updated, in RFC 3339 format.
 */
@Serializable
public data class UpdateApiKeyResponse(

  /** API key. */
  @SerialName(value = "key") val key: String,

  /** Date and time when the object was updated, in RFC 3339 format. */
  @SerialName(value = "updatedAt") val updatedAt: String,
) {}
