// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

export type ABTest = Record<string, unknown> & {
  /**
   * Unique A/B test identifier.
   */
  abTestID?: number | string | undefined;

  /**
   * A/B test name.
   */
  name?: string | undefined;

  /**
   * Current A/B test status.
   */
  status?: string | undefined;
};
