// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

export type ABTestResults = Record<string, unknown> & {
  /**
   * Unique A/B test identifier.
   */
  abTestID?: number | string | undefined;
};
