// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { BuiltInOperation } from './builtInOperation';
import type { BuiltInOperationType } from './builtInOperationType';
import type { BuiltInOperationValue } from './builtInOperationValue';


export type AttributeToUpdate = string | BuiltInOperation  ;
