// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.


/**
* URL for an image to show inside a banner.
*/
export type BannerImageUrl =  {

    url?:       string
    | undefined
 ;
} 



