// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { DictionaryAction } from './dictionaryAction';
import type { DictionaryEntry } from './dictionaryEntry';


export type BatchDictionaryEntriesRequest =  {

    action:       DictionaryAction
 ;

    body:       DictionaryEntry
 ;
} 



