// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { Exhaustive } from './exhaustive';
import type { FacetStats } from './facetStats';
import type { Hit } from './hit';
import type { Redirect } from './redirect';
import type { RenderingContent } from './renderingContent';
import type { BaseSearchResponse } from './baseSearchResponse';
import type { BrowsePagination } from './browsePagination';
import type { SearchHits } from './searchHits';
import type { Cursor } from './cursor';


export type BrowseResponse  <T = Record<string, unknown>>
 = BaseSearchResponse & BrowsePagination & SearchHits<T> & Cursor  ;
