// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { AdvancedSyntaxFeatures } from './advancedSyntaxFeatures';
import type { AlternativesAsExact } from './alternativesAsExact';
import type { AroundPrecision } from './aroundPrecision';
import type { AroundRadius } from './aroundRadius';
import type { BrowseParamsObject } from './browseParamsObject';
import type { Distinct } from './distinct';
import type { ExactOnSingleWordQuery } from './exactOnSingleWordQuery';
import type { FacetFilters } from './facetFilters';
import type { IgnorePlurals } from './ignorePlurals';
import type { InsideBoundingBox } from './insideBoundingBox';
import type { Mode } from './mode';
import type { NumericFilters } from './numericFilters';
import type { OptionalFilters } from './optionalFilters';
import type { OptionalWords } from './optionalWords';
import type { QueryType } from './queryType';
import type { ReRankingApplyFilter } from './reRankingApplyFilter';
import type { RemoveStopWords } from './removeStopWords';
import type { RemoveWordsIfNoResults } from './removeWordsIfNoResults';
import type { RenderingContent } from './renderingContent';
import type { SearchParamsString } from './searchParamsString';
import type { SemanticSearch } from './semanticSearch';
import type { SupportedLanguage } from './supportedLanguage';
import type { TagFilters } from './tagFilters';
import type { TypoTolerance } from './typoTolerance';


export type BrowseParams = BrowseParamsObject | SearchParamsString  ;
