// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.


/**
* Error.
*/
export type ErrorBase = Record<string, any> &  {

    message?:       string
    | undefined
 ;
} 



