// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { Acl } from './acl';
import type { BaseGetApiKeyResponse } from './baseGetApiKeyResponse';
import type { ApiKey } from './apiKey';


export type GetApiKeyResponse = BaseGetApiKeyResponse & ApiKey  ;
