// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.



export type GetObjectsResponse  <T = Record<string, unknown>>
 =  {

    /**
    * An optional status message.
    */
    message?:       string
    | undefined
 ;

    /**
    * Retrieved records.
    */
    results:     T[] ;
} 



