// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { HighlightResultOption } from './highlightResultOption';
import type { MatchLevel } from './matchLevel';


export type HighlightResult = HighlightResultOption | { [key: string]: HighlightResult; } | Array<HighlightResult>  ;
