// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.


/**
* Whether the whole query string matches or only a part.
*/
export type MatchLevel = 'none'|'partial'|'full'

