// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.


/**
* Operation to perform on the index.
*/
export type OperationType = 'move'|'copy'

