// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { PromoteObjectID } from './promoteObjectID';
import type { PromoteObjectIDs } from './promoteObjectIDs';


export type Promote = PromoteObjectIDs | PromoteObjectID  ;
