// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { SynonymHit } from './synonymHit';


export type SearchSynonymsResponse = Record<string, any> &  {

    /**
    * Matching synonyms.
    */
    hits:       Array<SynonymHit>
 ;

    /**
    * Number of results (hits).
    */
    nbHits:       number
 ;
} 



