// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { Exhaustive } from './exhaustive';
import type { FacetHits } from './facetHits';
import type { FacetStats } from './facetStats';
import type { Hit } from './hit';
import type { Redirect } from './redirect';
import type { RenderingContent } from './renderingContent';
import type { SearchForFacetValuesResponse } from './searchForFacetValuesResponse';
import type { SearchResponse } from './searchResponse';


export type SearchResult  <T = Record<string, unknown>>
 = SearchResponse<T> | SearchForFacetValuesResponse  ;
