// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

import type { MatchLevel } from './matchLevel';
import type { SnippetResultOption } from './snippetResultOption';


export type SnippetResult = SnippetResultOption | { [key: string]: SnippetResult; } | Array<SnippetResult>  ;
