// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.


/**
* Synonym type.
*/
export type SynonymType = 'synonym'|'onewaysynonym'|'altcorrection1'|'altcorrection2'|'placeholder'|'oneWaySynonym'|'altCorrection1'|'altCorrection2'

