// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.



export type WithPrimary =  {

    /**
    * Replica indices only: the name of the primary index for this replica. 
    */
    primary?:       string
    | undefined
 ;
} 



