/** Search API ## Client libraries Use Flapjack's API clients and libraries to reliably integrate Flapjack's APIs with
  * your apps. The official API clients are covered by Flapjack's [Service Level
  * Agreement](https://www.flapjack.io/policies/sla). For more information, see [Flapjack's
  * ecosystem](https://www.flapjack.io/doc/guides/getting-started/how-flapjack-works/in-depth/ecosystem). ## Base URLs
  * Base URLs for the Search API: - `https://{APPLICATION_ID}.flapjack.io` - `https://{APPLICATION_ID}-dsn.flapjack.io`.
  * If your subscription includes a [Distributed Search Network](https://dashboard.flapjack.io/infra), this ensures that
  * requests are sent to servers closest to users. Both URLs provide high availability by distributing requests with
  * load balancing. **All requests must use HTTPS.** ## Retry strategy To guarantee high availability, implement a retry
  * strategy for all API requests using the URLs of your servers as fallbacks: -
  * `https://{APPLICATION_ID}-1.flapjack.io` - `https://{APPLICATION_ID}-2.flapjack.io` -
  * `https://{APPLICATION_ID}-3.flapjack.io` These URLs use a different DNS provider than the primary URLs. Randomize
  * this list to ensure an even load across the three servers. All Flapjack API clients implement this retry strategy. ##
  * Authentication Add these headers to authenticate requests: - `x-algolia-application-id`. Your Flapjack application
  * ID. - `x-algolia-api-key`. An API key with the necessary permissions to make the request. The required access
  * control list (ACL) to make a request is listed in each endpoint's reference. You can find your application ID and
  * API key in the [Flapjack dashboard](https://dashboard.flapjack.io/account/api-keys). ## Request format Depending on
  * the endpoint, request bodies are either JSON objects or arrays of JSON objects. ## Parameters Parameters are passed
  * as query parameters for GET and DELETE requests, and in the request body for POST and PUT requests. Query parameters
  * must be [URL-encoded](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding). Non-ASCII characters must
  * be UTF-8 encoded. Plus characters (`+`) are interpreted as spaces. Arrays as query parameters must be one of: - A
  * comma-separated string: `attributesToRetrieve=title,description` - A URL-encoded JSON array:
  * `attributesToRetrieve=%5B%22title%22,%22description%22%D` ## Response status and errors The Search API returns JSON
  * responses. Since JSON doesn't guarantee any specific ordering, don't rely on the order of attributes in the API
  * response. Successful responses return `2xx` statuses. Client errors return `4xx` statuses. Server errors return
  * `5xx` statuses. Error responses have a `message` property with more information. ## Version The current version of
  * the Search API is version 1, indicated by the `/1/` in each endpoint's URL.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package flapjacksearch.search

import flapjacksearch.search.Acl._

/** API key object.
  *
  * @param acl
  *   Permissions that determine the type of API requests this key can make. The required ACL is listed in each
  *   endpoint's reference. For more information, see [access control
  *   list](https://www.flapjack.io/doc/guides/security/api-keys/#access-control-list-acl).
  * @param description
  *   Description of an API key to help you identify this API key.
  * @param indexes
  *   Index names or patterns that this API key can access. By default, an API key can access all indices in the same
  *   application. You can use leading and trailing wildcard characters (`*`): - `dev_*` matches all indices starting
  *   with \"dev_\" - `*_dev` matches all indices ending with \"_dev\" - `*_products_*` matches all indices containing
  *   \"_products_\".
  * @param maxHitsPerQuery
  *   Maximum number of results this API key can retrieve in one query. By default, there's no limit.
  * @param maxQueriesPerIPPerHour
  *   Maximum number of API requests allowed per IP address or [user
  *   token](https://www.flapjack.io/doc/guides/sending-events/concepts/usertoken) per hour. If this limit is reached,
  *   the API returns an error with status code `429`. By default, there's no limit.
  * @param queryParameters
  *   Query parameters to add when making API requests with this API key. To restrict this API key to specific IP
  *   addresses, add the `restrictSources` parameter. You can only add a single source, but you can provide a range of
  *   IP addresses. Creating an API key fails if the request is made from an IP address outside the restricted range.
  * @param referers
  *   Allowed HTTP referrers for this API key. By default, all referrers are allowed. You can use leading and trailing
  *   wildcard characters (`*`): - `https://flapjack.io/_*` allows all referrers starting with \"https://flapjack.io/\"
  *   \- `*.flapjack.io` allows all referrers ending with \".flapjack.io\" - `*flapjack.io*` allows all referrers in the
  *   domain \"flapjack.io\". Like all HTTP headers, referrers can be spoofed. Don't rely on them to secure your data.
  *   For more information, see [HTTP referrer
  *   restrictions](https://www.flapjack.io/doc/guides/security/security-best-practices/#http-referrers-restrictions).
  * @param validity
  *   Duration (in seconds) after which the API key expires. By default, API keys don't expire.
  */
case class ApiKey(
    acl: Seq[Acl],
    description: Option[String] = scala.None,
    indexes: Option[Seq[String]] = scala.None,
    maxHitsPerQuery: Option[Int] = scala.None,
    maxQueriesPerIPPerHour: Option[Int] = scala.None,
    queryParameters: Option[String] = scala.None,
    referers: Option[Seq[String]] = scala.None,
    validity: Option[Int] = scala.None
)
