// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

package com.flapjackhq.model.recommend;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;

/** Whether the whole query string matches or only a part. */
public enum MatchLevel {
  NONE("none"),

  PARTIAL("partial"),

  FULL("full");

  private final String value;

  MatchLevel(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MatchLevel fromValue(String value) {
    for (MatchLevel b : MatchLevel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
