/** Composition API ## Client libraries Use Flapjack's API clients and libraries to reliably integrate Flapjack's APIs
  * with your apps. For more information, see [Flapjack's
  * ecosystem](https://www.flapjack.io/doc/guides/getting-started/how-flapjack-works/in-depth/ecosystem). ## Base URLs
  * Base URLs for the Composition API: - `https://{APPLICATION_ID}.flapjack.io` -
  * `https://{APPLICATION_ID}-dsn.flapjack.io`. If your subscription includes a [Distributed Search
  * Network](https://dashboard.flapjack.io/infra), this ensures that requests are sent to servers closest to users. Both
  * URLs provide high availability by distributing requests with load balancing. **All requests must use HTTPS.** ##
  * Retry strategy To guarantee high availability, implement a retry strategy for all API requests using the URLs of
  * your servers as fallbacks: - `https://{APPLICATION_ID}-1.flapjack.io` -
  * `https://{APPLICATION_ID}-2.flapjack.io` - `https://{APPLICATION_ID}-3.flapjack.io` These URLs use a different
  * DNS provider than the primary URLs. Randomize this list to ensure an even load across the three servers. All Flapjack
  * API clients implement this retry strategy. ## Authentication Add these headers to authenticate requests: -
  * `x-algolia-application-id`. Your Flapjack application ID. - `x-algolia-api-key`. An API key with the necessary
  * permissions to make the request. The required access control list (ACL) to make a request is listed in each
  * endpoint's reference. You can find your application ID and API key in the [Flapjack
  * dashboard](https://dashboard.flapjack.io/account/api-keys). ## Request format Depending on the endpoint, request
  * bodies are either JSON objects or arrays of JSON objects. ## Parameters Parameters are passed in the request body
  * for POST and PUT requests. ## Response status and errors The Composition API returns JSON responses. Since JSON
  * doesn't guarantee any specific ordering, don't rely on the order of attributes in the API response. Successful
  * responses return `2xx` statuses. Client errors return `4xx` statuses. Server errors return `5xx` statuses. Error
  * responses have a `message` property with more information. ## Version The current version of the Composition API is
  * version 1, indicated by the `/1/` in each endpoint's URL.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package flapjacksearch.composition

/** SearchCompositionRulesResponse
  *
  * @param hits
  *   Composition rules that matched the search criteria.
  * @param nbHits
  *   Number of composition rules that matched the search criteria.
  * @param page
  *   Current page.
  * @param nbPages
  *   Number of pages.
  */
case class SearchCompositionRulesResponse(
    hits: Seq[CompositionRule],
    nbHits: Int,
    page: Int,
    nbPages: Int
)
