//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Insights;

/// <summary>
/// Defines PurchaseEvent
/// </summary>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<PurchaseEvent>))]
public enum PurchaseEvent
{
  /// <summary>
  /// Enum Purchase for value: purchase
  /// </summary>
  [JsonPropertyName("purchase")]
  Purchase = 1,
}
