// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.

package com.flapjackhq.model.composition;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;

/** Gets or Sets externalOrdering */
public enum ExternalOrdering {
  DEFAULT("default"),

  USER_DEFINED("userDefined");

  private final String value;

  ExternalOrdering(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ExternalOrdering fromValue(String value) {
    for (ExternalOrdering b : ExternalOrdering.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
