/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * The selected streams of an airbyte connector.
 *
 * @param streams
 */
@Serializable
public data class DockerStreamsInput(
  @SerialName(value = "streams") val streams: List<DockerStreams>
) : TaskInput {}
