/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*

/** Mapping format schema. */
@Serializable
public enum class MappingFormatSchema(public val value: kotlin.String) {

  @SerialName(value = "mappingkit/v1") MappingkitSlashV1("mappingkit/v1");

  override fun toString(): kotlin.String = value
}
