/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*

/** Task run status. */
@Serializable
public enum class RunStatus(public val value: kotlin.String) {

  @SerialName(value = "created") Created("created"),
  @SerialName(value = "started") Started("started"),
  @SerialName(value = "finished") Finished("finished"),
  @SerialName(value = "skipped") Skipped("skipped");

  override fun toString(): kotlin.String = value
}
