/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Trigger input for scheduled tasks.
 *
 * @param type
 * @param cron Cron expression for the task's schedule.
 */
@Serializable
public data class ScheduleTriggerInput(
  @SerialName(value = "type") val type: ScheduleTriggerType,

  /** Cron expression for the task's schedule. */
  @SerialName(value = "cron") val cron: String,
) : TaskCreateTrigger {}
