/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * SourceSearch
 *
 * @param sourceIDs
 */
@Serializable
public data class SourceSearch(@SerialName(value = "sourceIDs") val sourceIDs: List<String>) {}
