/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TaskSearch
 *
 * @param taskIDs
 */
@Serializable
public data class TaskSearch(@SerialName(value = "taskIDs") val taskIDs: List<String>) {}
