/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TransformationTryResponse
 *
 * @param payloads The array of stringified records returned by the transformation service.
 * @param error
 */
@Serializable
public data class TransformationTryResponse(

  /** The array of stringified records returned by the transformation service. */
  @SerialName(value = "payloads") val payloads: List<String>,
  @SerialName(value = "error") val error: TransformationError? = null,
) {}
