/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * The error if the transformation failed.
 *
 * @param code The error status code.
 * @param message A descriptive message explaining the failure.
 */
@Serializable
public data class TransformationError(

  /** The error status code. */
  @SerialName(value = "code") val code: Int? = null,

  /** A descriptive message explaining the failure. */
  @SerialName(value = "message") val message: String? = null,
) {}
