/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * TransformationSearch
 *
 * @param transformationIDs
 */
@Serializable
public data class TransformationSearch(
  @SerialName(value = "transformationIDs") val transformationIDs: List<String>
) {}
