/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/flapjackhq/sdk-automation. DO NOT EDIT.
 */
package com.flapjackhq.client.model.ingestion

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * Input for a no-code transformation that contains a series of steps.
 *
 * @param steps
 */
@Serializable
public data class TransformationNoCode(@SerialName(value = "steps") val steps: List<JsonObject>) :
  TransformationInput {}
