//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/flapjackhq/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Flapjack.Search.Serializer;

namespace Flapjack.Search.Models.Recommend;

/// <summary>
/// Trending items model.  Trending items are determined from the number of conversion events collected on them.
/// </summary>
/// <value>Trending items model.  Trending items are determined from the number of conversion events collected on them. </value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<TrendingItemsModel>))]
public enum TrendingItemsModel
{
  /// <summary>
  /// Enum TrendingItems for value: trending-items
  /// </summary>
  [JsonPropertyName("trending-items")]
  TrendingItems = 1,
}
